// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: cloche.proto

package clochepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RunWorkflowRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkflowName  string                 `protobuf:"bytes,1,opt,name=workflow_name,json=workflowName,proto3" json:"workflow_name,omitempty"`
	ProjectDir    string                 `protobuf:"bytes,2,opt,name=project_dir,json=projectDir,proto3" json:"project_dir,omitempty"`
	Image         string                 `protobuf:"bytes,3,opt,name=image,proto3" json:"image,omitempty"`
	Prompt        string                 `protobuf:"bytes,4,opt,name=prompt,proto3" json:"prompt,omitempty"`
	KeepContainer bool                   `protobuf:"varint,5,opt,name=keep_container,json=keepContainer,proto3" json:"keep_container,omitempty"`
	Title         string                 `protobuf:"bytes,6,opt,name=title,proto3" json:"title,omitempty"`
	IssueId       string                 `protobuf:"bytes,7,opt,name=issue_id,json=issueId,proto3" json:"issue_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunWorkflowRequest) Reset() {
	*x = RunWorkflowRequest{}
	mi := &file_cloche_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunWorkflowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunWorkflowRequest) ProtoMessage() {}

func (x *RunWorkflowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cloche_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunWorkflowRequest.ProtoReflect.Descriptor instead.
func (*RunWorkflowRequest) Descriptor() ([]byte, []int) {
	return file_cloche_proto_rawDescGZIP(), []int{0}
}

func (x *RunWorkflowRequest) GetWorkflowName() string {
	if x != nil {
		return x.WorkflowName
	}
	return ""
}

func (x *RunWorkflowRequest) GetProjectDir() string {
	if x != nil {
		return x.ProjectDir
	}
	return ""
}

func (x *RunWorkflowRequest) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *RunWorkflowRequest) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

func (x *RunWorkflowRequest) GetKeepContainer() bool {
	if x != nil {
		return x.KeepContainer
	}
	return false
}

func (x *RunWorkflowRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *RunWorkflowRequest) GetIssueId() string {
	if x != nil {
		return x.IssueId
	}
	return ""
}

type RunWorkflowResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RunId         string                 `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	TaskId        string                 `protobuf:"bytes,2,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	AttemptId     string                 `protobuf:"bytes,3,opt,name=attempt_id,json=attemptId,proto3" json:"attempt_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunWorkflowResponse) Reset() {
	*x = RunWorkflowResponse{}
	mi := &file_cloche_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunWorkflowResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunWorkflowResponse) ProtoMessage() {}

func (x *RunWorkflowResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cloche_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunWorkflowResponse.ProtoReflect.Descriptor instead.
func (*RunWorkflowResponse) Descriptor() ([]byte, []int) {
	return file_cloche_proto_rawDescGZIP(), []int{1}
}

func (x *RunWorkflowResponse) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *RunWorkflowResponse) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *RunWorkflowResponse) GetAttemptId() string {
	if x != nil {
		return x.AttemptId
	}
	return ""
}

type GetStatusRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	RunId string                 `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	// id accepts a task ID, attempt ID, or colon-delimited full step ID
	// (task_id:attempt_id:step_name). When set, takes priority over run_id.
	Id            string `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatusRequest) Reset() {
	*x = GetStatusRequest{}
	mi := &file_cloche_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatusRequest) ProtoMessage() {}

func (x *GetStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cloche_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatusRequest.ProtoReflect.Descriptor instead.
func (*GetStatusRequest) Descriptor() ([]byte, []int) {
	return file_cloche_proto_rawDescGZIP(), []int{2}
}

func (x *GetStatusRequest) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *GetStatusRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetStatusResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	RunId              string                 `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	WorkflowName       string                 `protobuf:"bytes,2,opt,name=workflow_name,json=workflowName,proto3" json:"workflow_name,omitempty"`
	State              string                 `protobuf:"bytes,3,opt,name=state,proto3" json:"state,omitempty"`
	CurrentStep        string                 `protobuf:"bytes,4,opt,name=current_step,json=currentStep,proto3" json:"current_step,omitempty"`
	StepExecutions     []*StepExecutionStatus `protobuf:"bytes,5,rep,name=step_executions,json=stepExecutions,proto3" json:"step_executions,omitempty"`
	ErrorMessage       string                 `protobuf:"bytes,6,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	ContainerId        string                 `protobuf:"bytes,7,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"`
	ContainerAlive     bool                   `protobuf:"varint,8,opt,name=container_alive,json=containerAlive,proto3" json:"container_alive,omitempty"`
	ContainerDeadSince string                 `protobuf:"bytes,9,opt,name=container_dead_since,json=containerDeadSince,proto3" json:"container_dead_since,omitempty"`
	Title              string                 `protobuf:"bytes,10,opt,name=title,proto3" json:"title,omitempty"`
	IsHost             bool                   `protobuf:"varint,11,opt,name=is_host,json=isHost,proto3" json:"is_host,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *GetStatusResponse) Reset() {
	*x = GetStatusResponse{}
	mi := &file_cloche_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatusResponse) ProtoMessage() {}

func (x *GetStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cloche_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatusResponse.ProtoReflect.Descriptor instead.
func (*GetStatusResponse) Descriptor() ([]byte, []int) {
	return file_cloche_proto_rawDescGZIP(), []int{3}
}

func (x *GetStatusResponse) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *GetStatusResponse) GetWorkflowName() string {
	if x != nil {
		return x.WorkflowName
	}
	return ""
}

func (x *GetStatusResponse) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *GetStatusResponse) GetCurrentStep() string {
	if x != nil {
		return x.CurrentStep
	}
	return ""
}

func (x *GetStatusResponse) GetStepExecutions() []*StepExecutionStatus {
	if x != nil {
		return x.StepExecutions
	}
	return nil
}

func (x *GetStatusResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *GetStatusResponse) GetContainerId() string {
	if x != nil {
		return x.ContainerId
	}
	return ""
}

func (x *GetStatusResponse) GetContainerAlive() bool {
	if x != nil {
		return x.ContainerAlive
	}
	return false
}

func (x *GetStatusResponse) GetContainerDeadSince() string {
	if x != nil {
		return x.ContainerDeadSince
	}
	return ""
}

func (x *GetStatusResponse) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *GetStatusResponse) GetIsHost() bool {
	if x != nil {
		return x.IsHost
	}
	return false
}

type StepExecutionStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StepName      string                 `protobuf:"bytes,1,opt,name=step_name,json=stepName,proto3" json:"step_name,omitempty"`
	Result        string                 `protobuf:"bytes,2,opt,name=result,proto3" json:"result,omitempty"`
	StartedAt     string                 `protobuf:"bytes,3,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	CompletedAt   string                 `protobuf:"bytes,4,opt,name=completed_at,json=completedAt,proto3" json:"completed_at,omitempty"`
	InputTokens   int64                  `protobuf:"varint,5,opt,name=input_tokens,json=inputTokens,proto3" json:"input_tokens,omitempty"`
	OutputTokens  int64                  `protobuf:"varint,6,opt,name=output_tokens,json=outputTokens,proto3" json:"output_tokens,omitempty"`
	AgentName     string                 `protobuf:"bytes,7,opt,name=agent_name,json=agentName,proto3" json:"agent_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StepExecutionStatus) Reset() {
	*x = StepExecutionStatus{}
	mi := &file_cloche_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StepExecutionStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StepExecutionStatus) ProtoMessage() {}

func (x *StepExecutionStatus) ProtoReflect() protoreflect.Message {
	mi := &file_cloche_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StepExecutionStatus.ProtoReflect.Descriptor instead.
func (*StepExecutionStatus) Descriptor() ([]byte, []int) {
	return file_cloche_proto_rawDescGZIP(), []int{4}
}

func (x *StepExecutionStatus) GetStepName() string {
	if x != nil {
		return x.StepName
	}
	return ""
}

func (x *StepExecutionStatus) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

func (x *StepExecutionStatus) GetStartedAt() string {
	if x != nil {
		return x.StartedAt
	}
	return ""
}

func (x *StepExecutionStatus) GetCompletedAt() string {
	if x != nil {
		return x.CompletedAt
	}
	return ""
}

func (x *StepExecutionStatus) GetInputTokens() int64 {
	if x != nil {
		return x.InputTokens
	}
	return 0
}

func (x *StepExecutionStatus) GetOutputTokens() int64 {
	if x != nil {
		return x.OutputTokens
	}
	return 0
}

func (x *StepExecutionStatus) GetAgentName() string {
	if x != nil {
		return x.AgentName
	}
	return ""
}

type StreamLogsRequest struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	RunId    string                 `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	StepName string                 `protobuf:"bytes,2,opt,name=step_name,json=stepName,proto3" json:"step_name,omitempty"`
	LogType  string                 `protobuf:"bytes,3,opt,name=log_type,json=logType,proto3" json:"log_type,omitempty"`
	Follow   bool                   `protobuf:"varint,4,opt,name=follow,proto3" json:"follow,omitempty"` // When true, stream existing logs then continue tailing new lines (like tail -f).
	// Passed via gRPC metadata header "x-cloche-follow" until proto is regenerated.
	Limit int32 `protobuf:"varint,5,opt,name=limit,proto3" json:"limit,omitempty"` // When > 0, display only the last N lines of output.
	// Passed via gRPC metadata header "x-cloche-limit" until proto is regenerated.
	// id accepts colon-delimited IDs at any level:
	//
	//	task_id                        — stream logs for the latest attempt of a task
	//	task_id:attempt_id             — stream logs for a specific attempt
	//	task_id:attempt_id:step_name   — stream logs for a specific step
	//
	// When set, takes priority over run_id + step_name.
	Id            string `protobuf:"bytes,6,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamLogsRequest) Reset() {
	*x = StreamLogsRequest{}
	mi := &file_cloche_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamLogsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamLogsRequest) ProtoMessage() {}

func (x *StreamLogsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cloche_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamLogsRequest.ProtoReflect.Descriptor instead.
func (*StreamLogsRequest) Descriptor() ([]byte, []int) {
	return file_cloche_proto_rawDescGZIP(), []int{5}
}

func (x *StreamLogsRequest) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *StreamLogsRequest) GetStepName() string {
	if x != nil {
		return x.StepName
	}
	return ""
}

func (x *StreamLogsRequest) GetLogType() string {
	if x != nil {
		return x.LogType
	}
	return ""
}

func (x *StreamLogsRequest) GetFollow() bool {
	if x != nil {
		return x.Follow
	}
	return false
}

func (x *StreamLogsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *StreamLogsRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type LogEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	StepName      string                 `protobuf:"bytes,2,opt,name=step_name,json=stepName,proto3" json:"step_name,omitempty"`
	Result        string                 `protobuf:"bytes,3,opt,name=result,proto3" json:"result,omitempty"`
	Message       string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	Timestamp     string                 `protobuf:"bytes,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogEntry) Reset() {
	*x = LogEntry{}
	mi := &file_cloche_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogEntry) ProtoMessage() {}

func (x *LogEntry) ProtoReflect() protoreflect.Message {
	mi := &file_cloche_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogEntry.ProtoReflect.Descriptor instead.
func (*LogEntry) Descriptor() ([]byte, []int) {
	return file_cloche_proto_rawDescGZIP(), []int{6}
}

func (x *LogEntry) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *LogEntry) GetStepName() string {
	if x != nil {
		return x.StepName
	}
	return ""
}

func (x *LogEntry) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

func (x *LogEntry) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *LogEntry) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

// StopRunRequest stops all active runs for the given task.
// Note: the field is named task_id; the wire field number 1 is preserved
// for compatibility with older clients that sent run_id.
type StopRunRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopRunRequest) Reset() {
	*x = StopRunRequest{}
	mi := &file_cloche_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopRunRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopRunRequest) ProtoMessage() {}

func (x *StopRunRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cloche_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopRunRequest.ProtoReflect.Descriptor instead.
func (*StopRunRequest) Descriptor() ([]byte, []int) {
	return file_cloche_proto_rawDescGZIP(), []int{7}
}

func (x *StopRunRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

type StopRunResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopRunResponse) Reset() {
	*x = StopRunResponse{}
	mi := &file_cloche_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopRunResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopRunResponse) ProtoMessage() {}

func (x *StopRunResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cloche_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopRunResponse.ProtoReflect.Descriptor instead.
func (*StopRunResponse) Descriptor() ([]byte, []int) {
	return file_cloche_proto_rawDescGZIP(), []int{8}
}

type ShutdownRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Force         bool                   `protobuf:"varint,1,opt,name=force,proto3" json:"force,omitempty"` // If false, reject shutdown when runs are active.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShutdownRequest) Reset() {
	*x = ShutdownRequest{}
	mi := &file_cloche_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShutdownRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShutdownRequest) ProtoMessage() {}

func (x *ShutdownRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cloche_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShutdownRequest.ProtoReflect.Descriptor instead.
func (*ShutdownRequest) Descriptor() ([]byte, []int) {
	return file_cloche_proto_rawDescGZIP(), []int{9}
}

func (x *ShutdownRequest) GetForce() bool {
	if x != nil {
		return x.Force
	}
	return false
}

type ShutdownResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShutdownResponse) Reset() {
	*x = ShutdownResponse{}
	mi := &file_cloche_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShutdownResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShutdownResponse) ProtoMessage() {}

func (x *ShutdownResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cloche_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShutdownResponse.ProtoReflect.Descriptor instead.
func (*ShutdownResponse) Descriptor() ([]byte, []int) {
	return file_cloche_proto_rawDescGZIP(), []int{10}
}

type DeleteContainerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteContainerRequest) Reset() {
	*x = DeleteContainerRequest{}
	mi := &file_cloche_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteContainerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteContainerRequest) ProtoMessage() {}

func (x *DeleteContainerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cloche_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteContainerRequest.ProtoReflect.Descriptor instead.
func (*DeleteContainerRequest) Descriptor() ([]byte, []int) {
	return file_cloche_proto_rawDescGZIP(), []int{11}
}

func (x *DeleteContainerRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteContainerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteContainerResponse) Reset() {
	*x = DeleteContainerResponse{}
	mi := &file_cloche_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteContainerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteContainerResponse) ProtoMessage() {}

func (x *DeleteContainerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cloche_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteContainerResponse.ProtoReflect.Descriptor instead.
func (*DeleteContainerResponse) Descriptor() ([]byte, []int) {
	return file_cloche_proto_rawDescGZIP(), []int{12}
}

type ListRunsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	All           bool                   `protobuf:"varint,1,opt,name=all,proto3" json:"all,omitempty"`
	ProjectDir    string                 `protobuf:"bytes,2,opt,name=project_dir,json=projectDir,proto3" json:"project_dir,omitempty"`
	State         string                 `protobuf:"bytes,3,opt,name=state,proto3" json:"state,omitempty"`
	Limit         int32                  `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	TaskId        string                 `protobuf:"bytes,5,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRunsRequest) Reset() {
	*x = ListRunsRequest{}
	mi := &file_cloche_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRunsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRunsRequest) ProtoMessage() {}

func (x *ListRunsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cloche_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRunsRequest.ProtoReflect.Descriptor instead.
func (*ListRunsRequest) Descriptor() ([]byte, []int) {
	return file_cloche_proto_rawDescGZIP(), []int{13}
}

func (x *ListRunsRequest) GetAll() bool {
	if x != nil {
		return x.All
	}
	return false
}

func (x *ListRunsRequest) GetProjectDir() string {
	if x != nil {
		return x.ProjectDir
	}
	return ""
}

func (x *ListRunsRequest) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *ListRunsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListRunsRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

type ListRunsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Runs          []*RunSummary          `protobuf:"bytes,1,rep,name=runs,proto3" json:"runs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRunsResponse) Reset() {
	*x = ListRunsResponse{}
	mi := &file_cloche_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRunsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRunsResponse) ProtoMessage() {}

func (x *ListRunsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cloche_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRunsResponse.ProtoReflect.Descriptor instead.
func (*ListRunsResponse) Descriptor() ([]byte, []int) {
	return file_cloche_proto_rawDescGZIP(), []int{14}
}

func (x *ListRunsResponse) GetRuns() []*RunSummary {
	if x != nil {
		return x.Runs
	}
	return nil
}

type RunSummary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RunId         string                 `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	WorkflowName  string                 `protobuf:"bytes,2,opt,name=workflow_name,json=workflowName,proto3" json:"workflow_name,omitempty"`
	State         string                 `protobuf:"bytes,3,opt,name=state,proto3" json:"state,omitempty"`
	StartedAt     string                 `protobuf:"bytes,4,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,5,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	ContainerId   string                 `protobuf:"bytes,6,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"`
	Title         string                 `protobuf:"bytes,7,opt,name=title,proto3" json:"title,omitempty"`
	IsHost        bool                   `protobuf:"varint,8,opt,name=is_host,json=isHost,proto3" json:"is_host,omitempty"`
	ProjectDir    string                 `protobuf:"bytes,9,opt,name=project_dir,json=projectDir,proto3" json:"project_dir,omitempty"`
	TaskId        string                 `protobuf:"bytes,10,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunSummary) Reset() {
	*x = RunSummary{}
	mi := &file_cloche_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunSummary) ProtoMessage() {}

func (x *RunSummary) ProtoReflect() protoreflect.Message {
	mi := &file_cloche_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunSummary.ProtoReflect.Descriptor instead.
func (*RunSummary) Descriptor() ([]byte, []int) {
	return file_cloche_proto_rawDescGZIP(), []int{15}
}

func (x *RunSummary) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *RunSummary) GetWorkflowName() string {
	if x != nil {
		return x.WorkflowName
	}
	return ""
}

func (x *RunSummary) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *RunSummary) GetStartedAt() string {
	if x != nil {
		return x.StartedAt
	}
	return ""
}

func (x *RunSummary) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *RunSummary) GetContainerId() string {
	if x != nil {
		return x.ContainerId
	}
	return ""
}

func (x *RunSummary) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *RunSummary) GetIsHost() bool {
	if x != nil {
		return x.IsHost
	}
	return false
}

func (x *RunSummary) GetProjectDir() string {
	if x != nil {
		return x.ProjectDir
	}
	return ""
}

func (x *RunSummary) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

type EnableLoopRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectDir    string                 `protobuf:"bytes,1,opt,name=project_dir,json=projectDir,proto3" json:"project_dir,omitempty"`
	MaxConcurrent int32                  `protobuf:"varint,2,opt,name=max_concurrent,json=maxConcurrent,proto3" json:"max_concurrent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnableLoopRequest) Reset() {
	*x = EnableLoopRequest{}
	mi := &file_cloche_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnableLoopRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnableLoopRequest) ProtoMessage() {}

func (x *EnableLoopRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cloche_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnableLoopRequest.ProtoReflect.Descriptor instead.
func (*EnableLoopRequest) Descriptor() ([]byte, []int) {
	return file_cloche_proto_rawDescGZIP(), []int{16}
}

func (x *EnableLoopRequest) GetProjectDir() string {
	if x != nil {
		return x.ProjectDir
	}
	return ""
}

func (x *EnableLoopRequest) GetMaxConcurrent() int32 {
	if x != nil {
		return x.MaxConcurrent
	}
	return 0
}

type EnableLoopResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnableLoopResponse) Reset() {
	*x = EnableLoopResponse{}
	mi := &file_cloche_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnableLoopResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnableLoopResponse) ProtoMessage() {}

func (x *EnableLoopResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cloche_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnableLoopResponse.ProtoReflect.Descriptor instead.
func (*EnableLoopResponse) Descriptor() ([]byte, []int) {
	return file_cloche_proto_rawDescGZIP(), []int{17}
}

type DisableLoopRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectDir    string                 `protobuf:"bytes,1,opt,name=project_dir,json=projectDir,proto3" json:"project_dir,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DisableLoopRequest) Reset() {
	*x = DisableLoopRequest{}
	mi := &file_cloche_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DisableLoopRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisableLoopRequest) ProtoMessage() {}

func (x *DisableLoopRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cloche_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisableLoopRequest.ProtoReflect.Descriptor instead.
func (*DisableLoopRequest) Descriptor() ([]byte, []int) {
	return file_cloche_proto_rawDescGZIP(), []int{18}
}

func (x *DisableLoopRequest) GetProjectDir() string {
	if x != nil {
		return x.ProjectDir
	}
	return ""
}

type DisableLoopResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DisableLoopResponse) Reset() {
	*x = DisableLoopResponse{}
	mi := &file_cloche_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DisableLoopResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisableLoopResponse) ProtoMessage() {}

func (x *DisableLoopResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cloche_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisableLoopResponse.ProtoReflect.Descriptor instead.
func (*DisableLoopResponse) Descriptor() ([]byte, []int) {
	return file_cloche_proto_rawDescGZIP(), []int{19}
}

type ResumeLoopRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectDir    string                 `protobuf:"bytes,1,opt,name=project_dir,json=projectDir,proto3" json:"project_dir,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResumeLoopRequest) Reset() {
	*x = ResumeLoopRequest{}
	mi := &file_cloche_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResumeLoopRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResumeLoopRequest) ProtoMessage() {}

func (x *ResumeLoopRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cloche_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResumeLoopRequest.ProtoReflect.Descriptor instead.
func (*ResumeLoopRequest) Descriptor() ([]byte, []int) {
	return file_cloche_proto_rawDescGZIP(), []int{20}
}

func (x *ResumeLoopRequest) GetProjectDir() string {
	if x != nil {
		return x.ProjectDir
	}
	return ""
}

type ResumeLoopResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResumeLoopResponse) Reset() {
	*x = ResumeLoopResponse{}
	mi := &file_cloche_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResumeLoopResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResumeLoopResponse) ProtoMessage() {}

func (x *ResumeLoopResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cloche_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResumeLoopResponse.ProtoReflect.Descriptor instead.
func (*ResumeLoopResponse) Descriptor() ([]byte, []int) {
	return file_cloche_proto_rawDescGZIP(), []int{21}
}

type GetProjectInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectDir    string                 `protobuf:"bytes,1,opt,name=project_dir,json=projectDir,proto3" json:"project_dir,omitempty"` // Resolve by absolute path (default: cwd)
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`                               // Resolve by project label (e.g. "cloche")
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProjectInfoRequest) Reset() {
	*x = GetProjectInfoRequest{}
	mi := &file_cloche_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProjectInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProjectInfoRequest) ProtoMessage() {}

func (x *GetProjectInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cloche_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProjectInfoRequest.ProtoReflect.Descriptor instead.
func (*GetProjectInfoRequest) Descriptor() ([]byte, []int) {
	return file_cloche_proto_rawDescGZIP(), []int{22}
}

func (x *GetProjectInfoRequest) GetProjectDir() string {
	if x != nil {
		return x.ProjectDir
	}
	return ""
}

func (x *GetProjectInfoRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GetProjectInfoResponse struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	ProjectDir             string                 `protobuf:"bytes,1,opt,name=project_dir,json=projectDir,proto3" json:"project_dir,omitempty"`
	Name                   string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Active                 bool                   `protobuf:"varint,3,opt,name=active,proto3" json:"active,omitempty"`
	Concurrency            int32                  `protobuf:"varint,4,opt,name=concurrency,proto3" json:"concurrency,omitempty"`
	StaggerSeconds         float64                `protobuf:"fixed64,5,opt,name=stagger_seconds,json=staggerSeconds,proto3" json:"stagger_seconds,omitempty"`
	DedupSeconds           float64                `protobuf:"fixed64,6,opt,name=dedup_seconds,json=dedupSeconds,proto3" json:"dedup_seconds,omitempty"`
	EvolutionEnabled       bool                   `protobuf:"varint,7,opt,name=evolution_enabled,json=evolutionEnabled,proto3" json:"evolution_enabled,omitempty"`
	LoopRunning            bool                   `protobuf:"varint,8,opt,name=loop_running,json=loopRunning,proto3" json:"loop_running,omitempty"`
	ActiveRuns             []*RunSummary          `protobuf:"bytes,9,rep,name=active_runs,json=activeRuns,proto3" json:"active_runs,omitempty"`
	ContainerWorkflows     []string               `protobuf:"bytes,10,rep,name=container_workflows,json=containerWorkflows,proto3" json:"container_workflows,omitempty"`
	HostWorkflows          []string               `protobuf:"bytes,11,rep,name=host_workflows,json=hostWorkflows,proto3" json:"host_workflows,omitempty"`
	StopOnError            bool                   `protobuf:"varint,12,opt,name=stop_on_error,json=stopOnError,proto3" json:"stop_on_error,omitempty"`
	ErrorHalted            bool                   `protobuf:"varint,13,opt,name=error_halted,json=errorHalted,proto3" json:"error_halted,omitempty"`                                    // true when loop is halted due to an unrecovered error
	HaltError              string                 `protobuf:"bytes,14,opt,name=halt_error,json=haltError,proto3" json:"halt_error,omitempty"`                                           // the error that caused the halt
	MaxConsecutiveFailures int32                  `protobuf:"varint,15,opt,name=max_consecutive_failures,json=maxConsecutiveFailures,proto3" json:"max_consecutive_failures,omitempty"` // halt loop after N consecutive failures
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *GetProjectInfoResponse) Reset() {
	*x = GetProjectInfoResponse{}
	mi := &file_cloche_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProjectInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProjectInfoResponse) ProtoMessage() {}

func (x *GetProjectInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cloche_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProjectInfoResponse.ProtoReflect.Descriptor instead.
func (*GetProjectInfoResponse) Descriptor() ([]byte, []int) {
	return file_cloche_proto_rawDescGZIP(), []int{23}
}

func (x *GetProjectInfoResponse) GetProjectDir() string {
	if x != nil {
		return x.ProjectDir
	}
	return ""
}

func (x *GetProjectInfoResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetProjectInfoResponse) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

func (x *GetProjectInfoResponse) GetConcurrency() int32 {
	if x != nil {
		return x.Concurrency
	}
	return 0
}

func (x *GetProjectInfoResponse) GetStaggerSeconds() float64 {
	if x != nil {
		return x.StaggerSeconds
	}
	return 0
}

func (x *GetProjectInfoResponse) GetDedupSeconds() float64 {
	if x != nil {
		return x.DedupSeconds
	}
	return 0
}

func (x *GetProjectInfoResponse) GetEvolutionEnabled() bool {
	if x != nil {
		return x.EvolutionEnabled
	}
	return false
}

func (x *GetProjectInfoResponse) GetLoopRunning() bool {
	if x != nil {
		return x.LoopRunning
	}
	return false
}

func (x *GetProjectInfoResponse) GetActiveRuns() []*RunSummary {
	if x != nil {
		return x.ActiveRuns
	}
	return nil
}

func (x *GetProjectInfoResponse) GetContainerWorkflows() []string {
	if x != nil {
		return x.ContainerWorkflows
	}
	return nil
}

func (x *GetProjectInfoResponse) GetHostWorkflows() []string {
	if x != nil {
		return x.HostWorkflows
	}
	return nil
}

func (x *GetProjectInfoResponse) GetStopOnError() bool {
	if x != nil {
		return x.StopOnError
	}
	return false
}

func (x *GetProjectInfoResponse) GetErrorHalted() bool {
	if x != nil {
		return x.ErrorHalted
	}
	return false
}

func (x *GetProjectInfoResponse) GetHaltError() string {
	if x != nil {
		return x.HaltError
	}
	return ""
}

func (x *GetProjectInfoResponse) GetMaxConsecutiveFailures() int32 {
	if x != nil {
		return x.MaxConsecutiveFailures
	}
	return 0
}

type GetVersionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVersionRequest) Reset() {
	*x = GetVersionRequest{}
	mi := &file_cloche_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVersionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVersionRequest) ProtoMessage() {}

func (x *GetVersionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cloche_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVersionRequest.ProtoReflect.Descriptor instead.
func (*GetVersionRequest) Descriptor() ([]byte, []int) {
	return file_cloche_proto_rawDescGZIP(), []int{24}
}

type GetVersionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVersionResponse) Reset() {
	*x = GetVersionResponse{}
	mi := &file_cloche_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVersionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVersionResponse) ProtoMessage() {}

func (x *GetVersionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cloche_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVersionResponse.ProtoReflect.Descriptor instead.
func (*GetVersionResponse) Descriptor() ([]byte, []int) {
	return file_cloche_proto_rawDescGZIP(), []int{25}
}

func (x *GetVersionResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

// ListTasks replaces ListRuns as the primary task-oriented listing RPC.
type ListTasksRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	All           bool                   `protobuf:"varint,1,opt,name=all,proto3" json:"all,omitempty"`
	ProjectDir    string                 `protobuf:"bytes,2,opt,name=project_dir,json=projectDir,proto3" json:"project_dir,omitempty"`
	State         string                 `protobuf:"bytes,3,opt,name=state,proto3" json:"state,omitempty"`
	Limit         int32                  `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTasksRequest) Reset() {
	*x = ListTasksRequest{}
	mi := &file_cloche_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTasksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTasksRequest) ProtoMessage() {}

func (x *ListTasksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cloche_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTasksRequest.ProtoReflect.Descriptor instead.
func (*ListTasksRequest) Descriptor() ([]byte, []int) {
	return file_cloche_proto_rawDescGZIP(), []int{26}
}

func (x *ListTasksRequest) GetAll() bool {
	if x != nil {
		return x.All
	}
	return false
}

func (x *ListTasksRequest) GetProjectDir() string {
	if x != nil {
		return x.ProjectDir
	}
	return ""
}

func (x *ListTasksRequest) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *ListTasksRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type TaskSummary struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TaskId          string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Title           string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Status          string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	ProjectDir      string                 `protobuf:"bytes,4,opt,name=project_dir,json=projectDir,proto3" json:"project_dir,omitempty"`
	CreatedAt       string                 `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	LatestAttemptId string                 `protobuf:"bytes,6,opt,name=latest_attempt_id,json=latestAttemptId,proto3" json:"latest_attempt_id,omitempty"`
	AttemptCount    int32                  `protobuf:"varint,7,opt,name=attempt_count,json=attemptCount,proto3" json:"attempt_count,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *TaskSummary) Reset() {
	*x = TaskSummary{}
	mi := &file_cloche_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskSummary) ProtoMessage() {}

func (x *TaskSummary) ProtoReflect() protoreflect.Message {
	mi := &file_cloche_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskSummary.ProtoReflect.Descriptor instead.
func (*TaskSummary) Descriptor() ([]byte, []int) {
	return file_cloche_proto_rawDescGZIP(), []int{27}
}

func (x *TaskSummary) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *TaskSummary) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *TaskSummary) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *TaskSummary) GetProjectDir() string {
	if x != nil {
		return x.ProjectDir
	}
	return ""
}

func (x *TaskSummary) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *TaskSummary) GetLatestAttemptId() string {
	if x != nil {
		return x.LatestAttemptId
	}
	return ""
}

func (x *TaskSummary) GetAttemptCount() int32 {
	if x != nil {
		return x.AttemptCount
	}
	return 0
}

type ListTasksResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tasks         []*TaskSummary         `protobuf:"bytes,1,rep,name=tasks,proto3" json:"tasks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTasksResponse) Reset() {
	*x = ListTasksResponse{}
	mi := &file_cloche_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTasksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTasksResponse) ProtoMessage() {}

func (x *ListTasksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cloche_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTasksResponse.ProtoReflect.Descriptor instead.
func (*ListTasksResponse) Descriptor() ([]byte, []int) {
	return file_cloche_proto_rawDescGZIP(), []int{28}
}

func (x *ListTasksResponse) GetTasks() []*TaskSummary {
	if x != nil {
		return x.Tasks
	}
	return nil
}

type GetTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTaskRequest) Reset() {
	*x = GetTaskRequest{}
	mi := &file_cloche_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTaskRequest) ProtoMessage() {}

func (x *GetTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cloche_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTaskRequest.ProtoReflect.Descriptor instead.
func (*GetTaskRequest) Descriptor() ([]byte, []int) {
	return file_cloche_proto_rawDescGZIP(), []int{29}
}

func (x *GetTaskRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

type AttemptSummary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AttemptId     string                 `protobuf:"bytes,1,opt,name=attempt_id,json=attemptId,proto3" json:"attempt_id,omitempty"`
	TaskId        string                 `protobuf:"bytes,2,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Result        string                 `protobuf:"bytes,3,opt,name=result,proto3" json:"result,omitempty"`
	StartedAt     string                 `protobuf:"bytes,4,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	EndedAt       string                 `protobuf:"bytes,5,opt,name=ended_at,json=endedAt,proto3" json:"ended_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AttemptSummary) Reset() {
	*x = AttemptSummary{}
	mi := &file_cloche_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttemptSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttemptSummary) ProtoMessage() {}

func (x *AttemptSummary) ProtoReflect() protoreflect.Message {
	mi := &file_cloche_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttemptSummary.ProtoReflect.Descriptor instead.
func (*AttemptSummary) Descriptor() ([]byte, []int) {
	return file_cloche_proto_rawDescGZIP(), []int{30}
}

func (x *AttemptSummary) GetAttemptId() string {
	if x != nil {
		return x.AttemptId
	}
	return ""
}

func (x *AttemptSummary) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *AttemptSummary) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

func (x *AttemptSummary) GetStartedAt() string {
	if x != nil {
		return x.StartedAt
	}
	return ""
}

func (x *AttemptSummary) GetEndedAt() string {
	if x != nil {
		return x.EndedAt
	}
	return ""
}

type GetTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	ProjectDir    string                 `protobuf:"bytes,4,opt,name=project_dir,json=projectDir,proto3" json:"project_dir,omitempty"`
	Attempts      []*AttemptSummary      `protobuf:"bytes,5,rep,name=attempts,proto3" json:"attempts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTaskResponse) Reset() {
	*x = GetTaskResponse{}
	mi := &file_cloche_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTaskResponse) ProtoMessage() {}

func (x *GetTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cloche_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTaskResponse.ProtoReflect.Descriptor instead.
func (*GetTaskResponse) Descriptor() ([]byte, []int) {
	return file_cloche_proto_rawDescGZIP(), []int{31}
}

func (x *GetTaskResponse) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *GetTaskResponse) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *GetTaskResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *GetTaskResponse) GetProjectDir() string {
	if x != nil {
		return x.ProjectDir
	}
	return ""
}

func (x *GetTaskResponse) GetAttempts() []*AttemptSummary {
	if x != nil {
		return x.Attempts
	}
	return nil
}

type GetAttemptRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AttemptId     string                 `protobuf:"bytes,1,opt,name=attempt_id,json=attemptId,proto3" json:"attempt_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAttemptRequest) Reset() {
	*x = GetAttemptRequest{}
	mi := &file_cloche_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAttemptRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAttemptRequest) ProtoMessage() {}

func (x *GetAttemptRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cloche_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAttemptRequest.ProtoReflect.Descriptor instead.
func (*GetAttemptRequest) Descriptor() ([]byte, []int) {
	return file_cloche_proto_rawDescGZIP(), []int{32}
}

func (x *GetAttemptRequest) GetAttemptId() string {
	if x != nil {
		return x.AttemptId
	}
	return ""
}

type GetAttemptResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AttemptId     string                 `protobuf:"bytes,1,opt,name=attempt_id,json=attemptId,proto3" json:"attempt_id,omitempty"`
	TaskId        string                 `protobuf:"bytes,2,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Result        string                 `protobuf:"bytes,3,opt,name=result,proto3" json:"result,omitempty"`
	StartedAt     string                 `protobuf:"bytes,4,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	EndedAt       string                 `protobuf:"bytes,5,opt,name=ended_at,json=endedAt,proto3" json:"ended_at,omitempty"`
	RunId         string                 `protobuf:"bytes,6,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAttemptResponse) Reset() {
	*x = GetAttemptResponse{}
	mi := &file_cloche_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAttemptResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAttemptResponse) ProtoMessage() {}

func (x *GetAttemptResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cloche_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAttemptResponse.ProtoReflect.Descriptor instead.
func (*GetAttemptResponse) Descriptor() ([]byte, []int) {
	return file_cloche_proto_rawDescGZIP(), []int{33}
}

func (x *GetAttemptResponse) GetAttemptId() string {
	if x != nil {
		return x.AttemptId
	}
	return ""
}

func (x *GetAttemptResponse) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *GetAttemptResponse) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

func (x *GetAttemptResponse) GetStartedAt() string {
	if x != nil {
		return x.StartedAt
	}
	return ""
}

func (x *GetAttemptResponse) GetEndedAt() string {
	if x != nil {
		return x.EndedAt
	}
	return ""
}

func (x *GetAttemptResponse) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

// CompleteRequest carries the current command-line state for shell completion.
// Words contains all tokens (including "cloche" at index 0).
// cur_idx is the index within words of the token being completed.
// project_dir is optional; used to enumerate workflow names.
type CompleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Words         []string               `protobuf:"bytes,1,rep,name=words,proto3" json:"words,omitempty"`
	CurIdx        int32                  `protobuf:"varint,2,opt,name=cur_idx,json=curIdx,proto3" json:"cur_idx,omitempty"`
	ProjectDir    string                 `protobuf:"bytes,3,opt,name=project_dir,json=projectDir,proto3" json:"project_dir,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompleteRequest) Reset() {
	*x = CompleteRequest{}
	mi := &file_cloche_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteRequest) ProtoMessage() {}

func (x *CompleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cloche_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteRequest.ProtoReflect.Descriptor instead.
func (*CompleteRequest) Descriptor() ([]byte, []int) {
	return file_cloche_proto_rawDescGZIP(), []int{34}
}

func (x *CompleteRequest) GetWords() []string {
	if x != nil {
		return x.Words
	}
	return nil
}

func (x *CompleteRequest) GetCurIdx() int32 {
	if x != nil {
		return x.CurIdx
	}
	return 0
}

func (x *CompleteRequest) GetProjectDir() string {
	if x != nil {
		return x.ProjectDir
	}
	return ""
}

type CompleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Completions   []string               `protobuf:"bytes,1,rep,name=completions,proto3" json:"completions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompleteResponse) Reset() {
	*x = CompleteResponse{}
	mi := &file_cloche_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteResponse) ProtoMessage() {}

func (x *CompleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cloche_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteResponse.ProtoReflect.Descriptor instead.
func (*CompleteResponse) Descriptor() ([]byte, []int) {
	return file_cloche_proto_rawDescGZIP(), []int{35}
}

func (x *CompleteResponse) GetCompletions() []string {
	if x != nil {
		return x.Completions
	}
	return nil
}

type GetUsageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectDir    string                 `protobuf:"bytes,1,opt,name=project_dir,json=projectDir,proto3" json:"project_dir,omitempty"`           // empty = global
	AgentName     string                 `protobuf:"bytes,2,opt,name=agent_name,json=agentName,proto3" json:"agent_name,omitempty"`              // empty = all agents
	WindowSeconds int64                  `protobuf:"varint,3,opt,name=window_seconds,json=windowSeconds,proto3" json:"window_seconds,omitempty"` // 0 = all time
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUsageRequest) Reset() {
	*x = GetUsageRequest{}
	mi := &file_cloche_proto_msgTypes[36]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUsageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUsageRequest) ProtoMessage() {}

func (x *GetUsageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cloche_proto_msgTypes[36]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUsageRequest.ProtoReflect.Descriptor instead.
func (*GetUsageRequest) Descriptor() ([]byte, []int) {
	return file_cloche_proto_rawDescGZIP(), []int{36}
}

func (x *GetUsageRequest) GetProjectDir() string {
	if x != nil {
		return x.ProjectDir
	}
	return ""
}

func (x *GetUsageRequest) GetAgentName() string {
	if x != nil {
		return x.AgentName
	}
	return ""
}

func (x *GetUsageRequest) GetWindowSeconds() int64 {
	if x != nil {
		return x.WindowSeconds
	}
	return 0
}

type GetUsageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Summaries     []*UsageSummary        `protobuf:"bytes,1,rep,name=summaries,proto3" json:"summaries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUsageResponse) Reset() {
	*x = GetUsageResponse{}
	mi := &file_cloche_proto_msgTypes[37]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUsageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUsageResponse) ProtoMessage() {}

func (x *GetUsageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cloche_proto_msgTypes[37]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUsageResponse.ProtoReflect.Descriptor instead.
func (*GetUsageResponse) Descriptor() ([]byte, []int) {
	return file_cloche_proto_rawDescGZIP(), []int{37}
}

func (x *GetUsageResponse) GetSummaries() []*UsageSummary {
	if x != nil {
		return x.Summaries
	}
	return nil
}

type UsageSummary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentName     string                 `protobuf:"bytes,1,opt,name=agent_name,json=agentName,proto3" json:"agent_name,omitempty"`
	InputTokens   int64                  `protobuf:"varint,2,opt,name=input_tokens,json=inputTokens,proto3" json:"input_tokens,omitempty"`
	OutputTokens  int64                  `protobuf:"varint,3,opt,name=output_tokens,json=outputTokens,proto3" json:"output_tokens,omitempty"`
	TotalTokens   int64                  `protobuf:"varint,4,opt,name=total_tokens,json=totalTokens,proto3" json:"total_tokens,omitempty"`
	BurnRate      float64                `protobuf:"fixed64,5,opt,name=burn_rate,json=burnRate,proto3" json:"burn_rate,omitempty"` // tokens per hour
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UsageSummary) Reset() {
	*x = UsageSummary{}
	mi := &file_cloche_proto_msgTypes[38]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UsageSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UsageSummary) ProtoMessage() {}

func (x *UsageSummary) ProtoReflect() protoreflect.Message {
	mi := &file_cloche_proto_msgTypes[38]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UsageSummary.ProtoReflect.Descriptor instead.
func (*UsageSummary) Descriptor() ([]byte, []int) {
	return file_cloche_proto_rawDescGZIP(), []int{38}
}

func (x *UsageSummary) GetAgentName() string {
	if x != nil {
		return x.AgentName
	}
	return ""
}

func (x *UsageSummary) GetInputTokens() int64 {
	if x != nil {
		return x.InputTokens
	}
	return 0
}

func (x *UsageSummary) GetOutputTokens() int64 {
	if x != nil {
		return x.OutputTokens
	}
	return 0
}

func (x *UsageSummary) GetTotalTokens() int64 {
	if x != nil {
		return x.TotalTokens
	}
	return 0
}

func (x *UsageSummary) GetBurnRate() float64 {
	if x != nil {
		return x.BurnRate
	}
	return 0
}

// ConsoleInput is sent from the CLI to the daemon over the Console stream.
// The first message must have payload set to start.
type ConsoleInput struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*ConsoleInput_Start
	//	*ConsoleInput_Stdin
	//	*ConsoleInput_Resize
	Payload       isConsoleInput_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConsoleInput) Reset() {
	*x = ConsoleInput{}
	mi := &file_cloche_proto_msgTypes[39]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsoleInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsoleInput) ProtoMessage() {}

func (x *ConsoleInput) ProtoReflect() protoreflect.Message {
	mi := &file_cloche_proto_msgTypes[39]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsoleInput.ProtoReflect.Descriptor instead.
func (*ConsoleInput) Descriptor() ([]byte, []int) {
	return file_cloche_proto_rawDescGZIP(), []int{39}
}

func (x *ConsoleInput) GetPayload() isConsoleInput_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ConsoleInput) GetStart() *ConsoleStart {
	if x != nil {
		if x, ok := x.Payload.(*ConsoleInput_Start); ok {
			return x.Start
		}
	}
	return nil
}

func (x *ConsoleInput) GetStdin() []byte {
	if x != nil {
		if x, ok := x.Payload.(*ConsoleInput_Stdin); ok {
			return x.Stdin
		}
	}
	return nil
}

func (x *ConsoleInput) GetResize() *TerminalSize {
	if x != nil {
		if x, ok := x.Payload.(*ConsoleInput_Resize); ok {
			return x.Resize
		}
	}
	return nil
}

type isConsoleInput_Payload interface {
	isConsoleInput_Payload()
}

type ConsoleInput_Start struct {
	Start *ConsoleStart `protobuf:"bytes,1,opt,name=start,proto3,oneof"` // First message: session configuration
}

type ConsoleInput_Stdin struct {
	Stdin []byte `protobuf:"bytes,2,opt,name=stdin,proto3,oneof"` // Subsequent: raw terminal input bytes
}

type ConsoleInput_Resize struct {
	Resize *TerminalSize `protobuf:"bytes,3,opt,name=resize,proto3,oneof"` // Terminal resize event
}

func (*ConsoleInput_Start) isConsoleInput_Payload() {}

func (*ConsoleInput_Stdin) isConsoleInput_Payload() {}

func (*ConsoleInput_Resize) isConsoleInput_Payload() {}

// ConsoleOutput is sent from the daemon to the CLI over the Console stream.
type ConsoleOutput struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*ConsoleOutput_Started
	//	*ConsoleOutput_Stdout
	//	*ConsoleOutput_Exited
	Payload       isConsoleOutput_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConsoleOutput) Reset() {
	*x = ConsoleOutput{}
	mi := &file_cloche_proto_msgTypes[40]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsoleOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsoleOutput) ProtoMessage() {}

func (x *ConsoleOutput) ProtoReflect() protoreflect.Message {
	mi := &file_cloche_proto_msgTypes[40]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsoleOutput.ProtoReflect.Descriptor instead.
func (*ConsoleOutput) Descriptor() ([]byte, []int) {
	return file_cloche_proto_rawDescGZIP(), []int{40}
}

func (x *ConsoleOutput) GetPayload() isConsoleOutput_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ConsoleOutput) GetStarted() *ConsoleStarted {
	if x != nil {
		if x, ok := x.Payload.(*ConsoleOutput_Started); ok {
			return x.Started
		}
	}
	return nil
}

func (x *ConsoleOutput) GetStdout() []byte {
	if x != nil {
		if x, ok := x.Payload.(*ConsoleOutput_Stdout); ok {
			return x.Stdout
		}
	}
	return nil
}

func (x *ConsoleOutput) GetExited() *ConsoleExited {
	if x != nil {
		if x, ok := x.Payload.(*ConsoleOutput_Exited); ok {
			return x.Exited
		}
	}
	return nil
}

type isConsoleOutput_Payload interface {
	isConsoleOutput_Payload()
}

type ConsoleOutput_Started struct {
	Started *ConsoleStarted `protobuf:"bytes,1,opt,name=started,proto3,oneof"` // First response: container info
}

type ConsoleOutput_Stdout struct {
	Stdout []byte `protobuf:"bytes,2,opt,name=stdout,proto3,oneof"` // Subsequent: raw terminal output bytes
}

type ConsoleOutput_Exited struct {
	Exited *ConsoleExited `protobuf:"bytes,3,opt,name=exited,proto3,oneof"` // Final message: process exit status
}

func (*ConsoleOutput_Started) isConsoleOutput_Payload() {}

func (*ConsoleOutput_Stdout) isConsoleOutput_Payload() {}

func (*ConsoleOutput_Exited) isConsoleOutput_Payload() {}

// ConsoleStart is the first ConsoleInput payload, configuring the session.
type ConsoleStart struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectDir    string                 `protobuf:"bytes,1,opt,name=project_dir,json=projectDir,proto3" json:"project_dir,omitempty"`
	AgentCommand  string                 `protobuf:"bytes,2,opt,name=agent_command,json=agentCommand,proto3" json:"agent_command,omitempty"` // empty = use resolution chain
	Rows          uint32                 `protobuf:"varint,3,opt,name=rows,proto3" json:"rows,omitempty"`
	Cols          uint32                 `protobuf:"varint,4,opt,name=cols,proto3" json:"cols,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConsoleStart) Reset() {
	*x = ConsoleStart{}
	mi := &file_cloche_proto_msgTypes[41]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsoleStart) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsoleStart) ProtoMessage() {}

func (x *ConsoleStart) ProtoReflect() protoreflect.Message {
	mi := &file_cloche_proto_msgTypes[41]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsoleStart.ProtoReflect.Descriptor instead.
func (*ConsoleStart) Descriptor() ([]byte, []int) {
	return file_cloche_proto_rawDescGZIP(), []int{41}
}

func (x *ConsoleStart) GetProjectDir() string {
	if x != nil {
		return x.ProjectDir
	}
	return ""
}

func (x *ConsoleStart) GetAgentCommand() string {
	if x != nil {
		return x.AgentCommand
	}
	return ""
}

func (x *ConsoleStart) GetRows() uint32 {
	if x != nil {
		return x.Rows
	}
	return 0
}

func (x *ConsoleStart) GetCols() uint32 {
	if x != nil {
		return x.Cols
	}
	return 0
}

// ConsoleStarted is the first ConsoleOutput payload, sent after the container starts.
type ConsoleStarted struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContainerId   string                 `protobuf:"bytes,1,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"`
	RunId         string                 `protobuf:"bytes,2,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConsoleStarted) Reset() {
	*x = ConsoleStarted{}
	mi := &file_cloche_proto_msgTypes[42]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsoleStarted) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsoleStarted) ProtoMessage() {}

func (x *ConsoleStarted) ProtoReflect() protoreflect.Message {
	mi := &file_cloche_proto_msgTypes[42]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsoleStarted.ProtoReflect.Descriptor instead.
func (*ConsoleStarted) Descriptor() ([]byte, []int) {
	return file_cloche_proto_rawDescGZIP(), []int{42}
}

func (x *ConsoleStarted) GetContainerId() string {
	if x != nil {
		return x.ContainerId
	}
	return ""
}

func (x *ConsoleStarted) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

// TerminalSize carries terminal dimensions for resize events.
type TerminalSize struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rows          uint32                 `protobuf:"varint,1,opt,name=rows,proto3" json:"rows,omitempty"`
	Cols          uint32                 `protobuf:"varint,2,opt,name=cols,proto3" json:"cols,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TerminalSize) Reset() {
	*x = TerminalSize{}
	mi := &file_cloche_proto_msgTypes[43]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TerminalSize) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TerminalSize) ProtoMessage() {}

func (x *TerminalSize) ProtoReflect() protoreflect.Message {
	mi := &file_cloche_proto_msgTypes[43]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TerminalSize.ProtoReflect.Descriptor instead.
func (*TerminalSize) Descriptor() ([]byte, []int) {
	return file_cloche_proto_rawDescGZIP(), []int{43}
}

func (x *TerminalSize) GetRows() uint32 {
	if x != nil {
		return x.Rows
	}
	return 0
}

func (x *TerminalSize) GetCols() uint32 {
	if x != nil {
		return x.Cols
	}
	return 0
}

// ConsoleExited is the final ConsoleOutput payload, sent when the agent process exits.
type ConsoleExited struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExitCode      int32                  `protobuf:"varint,1,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConsoleExited) Reset() {
	*x = ConsoleExited{}
	mi := &file_cloche_proto_msgTypes[44]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsoleExited) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsoleExited) ProtoMessage() {}

func (x *ConsoleExited) ProtoReflect() protoreflect.Message {
	mi := &file_cloche_proto_msgTypes[44]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsoleExited.ProtoReflect.Descriptor instead.
func (*ConsoleExited) Descriptor() ([]byte, []int) {
	return file_cloche_proto_rawDescGZIP(), []int{44}
}

func (x *ConsoleExited) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

var File_cloche_proto protoreflect.FileDescriptor

const file_cloche_proto_rawDesc = "" +
	"\n" +
	"\fcloche.proto\x12\tcloche.v1\"\xe0\x01\n" +
	"\x12RunWorkflowRequest\x12#\n" +
	"\rworkflow_name\x18\x01 \x01(\tR\fworkflowName\x12\x1f\n" +
	"\vproject_dir\x18\x02 \x01(\tR\n" +
	"projectDir\x12\x14\n" +
	"\x05image\x18\x03 \x01(\tR\x05image\x12\x16\n" +
	"\x06prompt\x18\x04 \x01(\tR\x06prompt\x12%\n" +
	"\x0ekeep_container\x18\x05 \x01(\bR\rkeepContainer\x12\x14\n" +
	"\x05title\x18\x06 \x01(\tR\x05title\x12\x19\n" +
	"\bissue_id\x18\a \x01(\tR\aissueId\"d\n" +
	"\x13RunWorkflowResponse\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\x12\x17\n" +
	"\atask_id\x18\x02 \x01(\tR\x06taskId\x12\x1d\n" +
	"\n" +
	"attempt_id\x18\x03 \x01(\tR\tattemptId\"9\n" +
	"\x10GetStatusRequest\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\"\xa3\x03\n" +
	"\x11GetStatusResponse\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\x12#\n" +
	"\rworkflow_name\x18\x02 \x01(\tR\fworkflowName\x12\x14\n" +
	"\x05state\x18\x03 \x01(\tR\x05state\x12!\n" +
	"\fcurrent_step\x18\x04 \x01(\tR\vcurrentStep\x12G\n" +
	"\x0fstep_executions\x18\x05 \x03(\v2\x1e.cloche.v1.StepExecutionStatusR\x0estepExecutions\x12#\n" +
	"\rerror_message\x18\x06 \x01(\tR\ferrorMessage\x12!\n" +
	"\fcontainer_id\x18\a \x01(\tR\vcontainerId\x12'\n" +
	"\x0fcontainer_alive\x18\b \x01(\bR\x0econtainerAlive\x120\n" +
	"\x14container_dead_since\x18\t \x01(\tR\x12containerDeadSince\x12\x14\n" +
	"\x05title\x18\n" +
	" \x01(\tR\x05title\x12\x17\n" +
	"\ais_host\x18\v \x01(\bR\x06isHost\"\xf3\x01\n" +
	"\x13StepExecutionStatus\x12\x1b\n" +
	"\tstep_name\x18\x01 \x01(\tR\bstepName\x12\x16\n" +
	"\x06result\x18\x02 \x01(\tR\x06result\x12\x1d\n" +
	"\n" +
	"started_at\x18\x03 \x01(\tR\tstartedAt\x12!\n" +
	"\fcompleted_at\x18\x04 \x01(\tR\vcompletedAt\x12!\n" +
	"\finput_tokens\x18\x05 \x01(\x03R\vinputTokens\x12#\n" +
	"\routput_tokens\x18\x06 \x01(\x03R\foutputTokens\x12\x1d\n" +
	"\n" +
	"agent_name\x18\a \x01(\tR\tagentName\"\xa0\x01\n" +
	"\x11StreamLogsRequest\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\x12\x1b\n" +
	"\tstep_name\x18\x02 \x01(\tR\bstepName\x12\x19\n" +
	"\blog_type\x18\x03 \x01(\tR\alogType\x12\x16\n" +
	"\x06follow\x18\x04 \x01(\bR\x06follow\x12\x14\n" +
	"\x05limit\x18\x05 \x01(\x05R\x05limit\x12\x0e\n" +
	"\x02id\x18\x06 \x01(\tR\x02id\"\x8b\x01\n" +
	"\bLogEntry\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x1b\n" +
	"\tstep_name\x18\x02 \x01(\tR\bstepName\x12\x16\n" +
	"\x06result\x18\x03 \x01(\tR\x06result\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\x12\x1c\n" +
	"\ttimestamp\x18\x05 \x01(\tR\ttimestamp\")\n" +
	"\x0eStopRunRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\"\x11\n" +
	"\x0fStopRunResponse\"'\n" +
	"\x0fShutdownRequest\x12\x14\n" +
	"\x05force\x18\x01 \x01(\bR\x05force\"\x12\n" +
	"\x10ShutdownResponse\"(\n" +
	"\x16DeleteContainerRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x19\n" +
	"\x17DeleteContainerResponse\"\x89\x01\n" +
	"\x0fListRunsRequest\x12\x10\n" +
	"\x03all\x18\x01 \x01(\bR\x03all\x12\x1f\n" +
	"\vproject_dir\x18\x02 \x01(\tR\n" +
	"projectDir\x12\x14\n" +
	"\x05state\x18\x03 \x01(\tR\x05state\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\x05R\x05limit\x12\x17\n" +
	"\atask_id\x18\x05 \x01(\tR\x06taskId\"=\n" +
	"\x10ListRunsResponse\x12)\n" +
	"\x04runs\x18\x01 \x03(\v2\x15.cloche.v1.RunSummaryR\x04runs\"\xae\x02\n" +
	"\n" +
	"RunSummary\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\x12#\n" +
	"\rworkflow_name\x18\x02 \x01(\tR\fworkflowName\x12\x14\n" +
	"\x05state\x18\x03 \x01(\tR\x05state\x12\x1d\n" +
	"\n" +
	"started_at\x18\x04 \x01(\tR\tstartedAt\x12#\n" +
	"\rerror_message\x18\x05 \x01(\tR\ferrorMessage\x12!\n" +
	"\fcontainer_id\x18\x06 \x01(\tR\vcontainerId\x12\x14\n" +
	"\x05title\x18\a \x01(\tR\x05title\x12\x17\n" +
	"\ais_host\x18\b \x01(\bR\x06isHost\x12\x1f\n" +
	"\vproject_dir\x18\t \x01(\tR\n" +
	"projectDir\x12\x17\n" +
	"\atask_id\x18\n" +
	" \x01(\tR\x06taskId\"[\n" +
	"\x11EnableLoopRequest\x12\x1f\n" +
	"\vproject_dir\x18\x01 \x01(\tR\n" +
	"projectDir\x12%\n" +
	"\x0emax_concurrent\x18\x02 \x01(\x05R\rmaxConcurrent\"\x14\n" +
	"\x12EnableLoopResponse\"5\n" +
	"\x12DisableLoopRequest\x12\x1f\n" +
	"\vproject_dir\x18\x01 \x01(\tR\n" +
	"projectDir\"\x15\n" +
	"\x13DisableLoopResponse\"4\n" +
	"\x11ResumeLoopRequest\x12\x1f\n" +
	"\vproject_dir\x18\x01 \x01(\tR\n" +
	"projectDir\"\x14\n" +
	"\x12ResumeLoopResponse\"L\n" +
	"\x15GetProjectInfoRequest\x12\x1f\n" +
	"\vproject_dir\x18\x01 \x01(\tR\n" +
	"projectDir\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"\xd5\x04\n" +
	"\x16GetProjectInfoResponse\x12\x1f\n" +
	"\vproject_dir\x18\x01 \x01(\tR\n" +
	"projectDir\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x16\n" +
	"\x06active\x18\x03 \x01(\bR\x06active\x12 \n" +
	"\vconcurrency\x18\x04 \x01(\x05R\vconcurrency\x12'\n" +
	"\x0fstagger_seconds\x18\x05 \x01(\x01R\x0estaggerSeconds\x12#\n" +
	"\rdedup_seconds\x18\x06 \x01(\x01R\fdedupSeconds\x12+\n" +
	"\x11evolution_enabled\x18\a \x01(\bR\x10evolutionEnabled\x12!\n" +
	"\floop_running\x18\b \x01(\bR\vloopRunning\x126\n" +
	"\vactive_runs\x18\t \x03(\v2\x15.cloche.v1.RunSummaryR\n" +
	"activeRuns\x12/\n" +
	"\x13container_workflows\x18\n" +
	" \x03(\tR\x12containerWorkflows\x12%\n" +
	"\x0ehost_workflows\x18\v \x03(\tR\rhostWorkflows\x12\"\n" +
	"\rstop_on_error\x18\f \x01(\bR\vstopOnError\x12!\n" +
	"\ferror_halted\x18\r \x01(\bR\verrorHalted\x12\x1d\n" +
	"\n" +
	"halt_error\x18\x0e \x01(\tR\thaltError\x128\n" +
	"\x18max_consecutive_failures\x18\x0f \x01(\x05R\x16maxConsecutiveFailures\"\x13\n" +
	"\x11GetVersionRequest\".\n" +
	"\x12GetVersionResponse\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\"q\n" +
	"\x10ListTasksRequest\x12\x10\n" +
	"\x03all\x18\x01 \x01(\bR\x03all\x12\x1f\n" +
	"\vproject_dir\x18\x02 \x01(\tR\n" +
	"projectDir\x12\x14\n" +
	"\x05state\x18\x03 \x01(\tR\x05state\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\x05R\x05limit\"\xe5\x01\n" +
	"\vTaskSummary\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x1f\n" +
	"\vproject_dir\x18\x04 \x01(\tR\n" +
	"projectDir\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\tR\tcreatedAt\x12*\n" +
	"\x11latest_attempt_id\x18\x06 \x01(\tR\x0flatestAttemptId\x12#\n" +
	"\rattempt_count\x18\a \x01(\x05R\fattemptCount\"A\n" +
	"\x11ListTasksResponse\x12,\n" +
	"\x05tasks\x18\x01 \x03(\v2\x16.cloche.v1.TaskSummaryR\x05tasks\")\n" +
	"\x0eGetTaskRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\"\x9a\x01\n" +
	"\x0eAttemptSummary\x12\x1d\n" +
	"\n" +
	"attempt_id\x18\x01 \x01(\tR\tattemptId\x12\x17\n" +
	"\atask_id\x18\x02 \x01(\tR\x06taskId\x12\x16\n" +
	"\x06result\x18\x03 \x01(\tR\x06result\x12\x1d\n" +
	"\n" +
	"started_at\x18\x04 \x01(\tR\tstartedAt\x12\x19\n" +
	"\bended_at\x18\x05 \x01(\tR\aendedAt\"\xb0\x01\n" +
	"\x0fGetTaskResponse\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x1f\n" +
	"\vproject_dir\x18\x04 \x01(\tR\n" +
	"projectDir\x125\n" +
	"\battempts\x18\x05 \x03(\v2\x19.cloche.v1.AttemptSummaryR\battempts\"2\n" +
	"\x11GetAttemptRequest\x12\x1d\n" +
	"\n" +
	"attempt_id\x18\x01 \x01(\tR\tattemptId\"\xb5\x01\n" +
	"\x12GetAttemptResponse\x12\x1d\n" +
	"\n" +
	"attempt_id\x18\x01 \x01(\tR\tattemptId\x12\x17\n" +
	"\atask_id\x18\x02 \x01(\tR\x06taskId\x12\x16\n" +
	"\x06result\x18\x03 \x01(\tR\x06result\x12\x1d\n" +
	"\n" +
	"started_at\x18\x04 \x01(\tR\tstartedAt\x12\x19\n" +
	"\bended_at\x18\x05 \x01(\tR\aendedAt\x12\x15\n" +
	"\x06run_id\x18\x06 \x01(\tR\x05runId\"a\n" +
	"\x0fCompleteRequest\x12\x14\n" +
	"\x05words\x18\x01 \x03(\tR\x05words\x12\x17\n" +
	"\acur_idx\x18\x02 \x01(\x05R\x06curIdx\x12\x1f\n" +
	"\vproject_dir\x18\x03 \x01(\tR\n" +
	"projectDir\"4\n" +
	"\x10CompleteResponse\x12 \n" +
	"\vcompletions\x18\x01 \x03(\tR\vcompletions\"x\n" +
	"\x0fGetUsageRequest\x12\x1f\n" +
	"\vproject_dir\x18\x01 \x01(\tR\n" +
	"projectDir\x12\x1d\n" +
	"\n" +
	"agent_name\x18\x02 \x01(\tR\tagentName\x12%\n" +
	"\x0ewindow_seconds\x18\x03 \x01(\x03R\rwindowSeconds\"I\n" +
	"\x10GetUsageResponse\x125\n" +
	"\tsummaries\x18\x01 \x03(\v2\x17.cloche.v1.UsageSummaryR\tsummaries\"\xb5\x01\n" +
	"\fUsageSummary\x12\x1d\n" +
	"\n" +
	"agent_name\x18\x01 \x01(\tR\tagentName\x12!\n" +
	"\finput_tokens\x18\x02 \x01(\x03R\vinputTokens\x12#\n" +
	"\routput_tokens\x18\x03 \x01(\x03R\foutputTokens\x12!\n" +
	"\ftotal_tokens\x18\x04 \x01(\x03R\vtotalTokens\x12\x1b\n" +
	"\tburn_rate\x18\x05 \x01(\x01R\bburnRate\"\x95\x01\n" +
	"\fConsoleInput\x12/\n" +
	"\x05start\x18\x01 \x01(\v2\x17.cloche.v1.ConsoleStartH\x00R\x05start\x12\x16\n" +
	"\x05stdin\x18\x02 \x01(\fH\x00R\x05stdin\x121\n" +
	"\x06resize\x18\x03 \x01(\v2\x17.cloche.v1.TerminalSizeH\x00R\x06resizeB\t\n" +
	"\apayload\"\x9f\x01\n" +
	"\rConsoleOutput\x125\n" +
	"\astarted\x18\x01 \x01(\v2\x19.cloche.v1.ConsoleStartedH\x00R\astarted\x12\x18\n" +
	"\x06stdout\x18\x02 \x01(\fH\x00R\x06stdout\x122\n" +
	"\x06exited\x18\x03 \x01(\v2\x18.cloche.v1.ConsoleExitedH\x00R\x06exitedB\t\n" +
	"\apayload\"|\n" +
	"\fConsoleStart\x12\x1f\n" +
	"\vproject_dir\x18\x01 \x01(\tR\n" +
	"projectDir\x12#\n" +
	"\ragent_command\x18\x02 \x01(\tR\fagentCommand\x12\x12\n" +
	"\x04rows\x18\x03 \x01(\rR\x04rows\x12\x12\n" +
	"\x04cols\x18\x04 \x01(\rR\x04cols\"J\n" +
	"\x0eConsoleStarted\x12!\n" +
	"\fcontainer_id\x18\x01 \x01(\tR\vcontainerId\x12\x15\n" +
	"\x06run_id\x18\x02 \x01(\tR\x05runId\"6\n" +
	"\fTerminalSize\x12\x12\n" +
	"\x04rows\x18\x01 \x01(\rR\x04rows\x12\x12\n" +
	"\x04cols\x18\x02 \x01(\rR\x04cols\",\n" +
	"\rConsoleExited\x12\x1b\n" +
	"\texit_code\x18\x01 \x01(\x05R\bexitCode2\xb5\n" +
	"\n" +
	"\rClocheService\x12L\n" +
	"\vRunWorkflow\x12\x1d.cloche.v1.RunWorkflowRequest\x1a\x1e.cloche.v1.RunWorkflowResponse\x12F\n" +
	"\tGetStatus\x12\x1b.cloche.v1.GetStatusRequest\x1a\x1c.cloche.v1.GetStatusResponse\x12A\n" +
	"\n" +
	"StreamLogs\x12\x1c.cloche.v1.StreamLogsRequest\x1a\x13.cloche.v1.LogEntry0\x01\x12@\n" +
	"\aStopRun\x12\x19.cloche.v1.StopRunRequest\x1a\x1a.cloche.v1.StopRunResponse\x12C\n" +
	"\bListRuns\x12\x1a.cloche.v1.ListRunsRequest\x1a\x1b.cloche.v1.ListRunsResponse\x12F\n" +
	"\tListTasks\x12\x1b.cloche.v1.ListTasksRequest\x1a\x1c.cloche.v1.ListTasksResponse\x12@\n" +
	"\aGetTask\x12\x19.cloche.v1.GetTaskRequest\x1a\x1a.cloche.v1.GetTaskResponse\x12I\n" +
	"\n" +
	"GetAttempt\x12\x1c.cloche.v1.GetAttemptRequest\x1a\x1d.cloche.v1.GetAttemptResponse\x12C\n" +
	"\bShutdown\x12\x1a.cloche.v1.ShutdownRequest\x1a\x1b.cloche.v1.ShutdownResponse\x12X\n" +
	"\x0fDeleteContainer\x12!.cloche.v1.DeleteContainerRequest\x1a\".cloche.v1.DeleteContainerResponse\x12I\n" +
	"\n" +
	"EnableLoop\x12\x1c.cloche.v1.EnableLoopRequest\x1a\x1d.cloche.v1.EnableLoopResponse\x12L\n" +
	"\vDisableLoop\x12\x1d.cloche.v1.DisableLoopRequest\x1a\x1e.cloche.v1.DisableLoopResponse\x12I\n" +
	"\n" +
	"ResumeLoop\x12\x1c.cloche.v1.ResumeLoopRequest\x1a\x1d.cloche.v1.ResumeLoopResponse\x12U\n" +
	"\x0eGetProjectInfo\x12 .cloche.v1.GetProjectInfoRequest\x1a!.cloche.v1.GetProjectInfoResponse\x12I\n" +
	"\n" +
	"GetVersion\x12\x1c.cloche.v1.GetVersionRequest\x1a\x1d.cloche.v1.GetVersionResponse\x12C\n" +
	"\bComplete\x12\x1a.cloche.v1.CompleteRequest\x1a\x1b.cloche.v1.CompleteResponse\x12C\n" +
	"\bGetUsage\x12\x1a.cloche.v1.GetUsageRequest\x1a\x1b.cloche.v1.GetUsageResponse\x12@\n" +
	"\aConsole\x12\x17.cloche.v1.ConsoleInput\x1a\x18.cloche.v1.ConsoleOutput(\x010\x01B+Z)github.com/cloche-dev/cloche/api/clochepbb\x06proto3"

var (
	file_cloche_proto_rawDescOnce sync.Once
	file_cloche_proto_rawDescData []byte
)

func file_cloche_proto_rawDescGZIP() []byte {
	file_cloche_proto_rawDescOnce.Do(func() {
		file_cloche_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cloche_proto_rawDesc), len(file_cloche_proto_rawDesc)))
	})
	return file_cloche_proto_rawDescData
}

var file_cloche_proto_msgTypes = make([]protoimpl.MessageInfo, 45)
var file_cloche_proto_goTypes = []any{
	(*RunWorkflowRequest)(nil),      // 0: cloche.v1.RunWorkflowRequest
	(*RunWorkflowResponse)(nil),     // 1: cloche.v1.RunWorkflowResponse
	(*GetStatusRequest)(nil),        // 2: cloche.v1.GetStatusRequest
	(*GetStatusResponse)(nil),       // 3: cloche.v1.GetStatusResponse
	(*StepExecutionStatus)(nil),     // 4: cloche.v1.StepExecutionStatus
	(*StreamLogsRequest)(nil),       // 5: cloche.v1.StreamLogsRequest
	(*LogEntry)(nil),                // 6: cloche.v1.LogEntry
	(*StopRunRequest)(nil),          // 7: cloche.v1.StopRunRequest
	(*StopRunResponse)(nil),         // 8: cloche.v1.StopRunResponse
	(*ShutdownRequest)(nil),         // 9: cloche.v1.ShutdownRequest
	(*ShutdownResponse)(nil),        // 10: cloche.v1.ShutdownResponse
	(*DeleteContainerRequest)(nil),  // 11: cloche.v1.DeleteContainerRequest
	(*DeleteContainerResponse)(nil), // 12: cloche.v1.DeleteContainerResponse
	(*ListRunsRequest)(nil),         // 13: cloche.v1.ListRunsRequest
	(*ListRunsResponse)(nil),        // 14: cloche.v1.ListRunsResponse
	(*RunSummary)(nil),              // 15: cloche.v1.RunSummary
	(*EnableLoopRequest)(nil),       // 16: cloche.v1.EnableLoopRequest
	(*EnableLoopResponse)(nil),      // 17: cloche.v1.EnableLoopResponse
	(*DisableLoopRequest)(nil),      // 18: cloche.v1.DisableLoopRequest
	(*DisableLoopResponse)(nil),     // 19: cloche.v1.DisableLoopResponse
	(*ResumeLoopRequest)(nil),       // 20: cloche.v1.ResumeLoopRequest
	(*ResumeLoopResponse)(nil),      // 21: cloche.v1.ResumeLoopResponse
	(*GetProjectInfoRequest)(nil),   // 22: cloche.v1.GetProjectInfoRequest
	(*GetProjectInfoResponse)(nil),  // 23: cloche.v1.GetProjectInfoResponse
	(*GetVersionRequest)(nil),       // 24: cloche.v1.GetVersionRequest
	(*GetVersionResponse)(nil),      // 25: cloche.v1.GetVersionResponse
	(*ListTasksRequest)(nil),        // 26: cloche.v1.ListTasksRequest
	(*TaskSummary)(nil),             // 27: cloche.v1.TaskSummary
	(*ListTasksResponse)(nil),       // 28: cloche.v1.ListTasksResponse
	(*GetTaskRequest)(nil),          // 29: cloche.v1.GetTaskRequest
	(*AttemptSummary)(nil),          // 30: cloche.v1.AttemptSummary
	(*GetTaskResponse)(nil),         // 31: cloche.v1.GetTaskResponse
	(*GetAttemptRequest)(nil),       // 32: cloche.v1.GetAttemptRequest
	(*GetAttemptResponse)(nil),      // 33: cloche.v1.GetAttemptResponse
	(*CompleteRequest)(nil),         // 34: cloche.v1.CompleteRequest
	(*CompleteResponse)(nil),        // 35: cloche.v1.CompleteResponse
	(*GetUsageRequest)(nil),         // 36: cloche.v1.GetUsageRequest
	(*GetUsageResponse)(nil),        // 37: cloche.v1.GetUsageResponse
	(*UsageSummary)(nil),            // 38: cloche.v1.UsageSummary
	(*ConsoleInput)(nil),            // 39: cloche.v1.ConsoleInput
	(*ConsoleOutput)(nil),           // 40: cloche.v1.ConsoleOutput
	(*ConsoleStart)(nil),            // 41: cloche.v1.ConsoleStart
	(*ConsoleStarted)(nil),          // 42: cloche.v1.ConsoleStarted
	(*TerminalSize)(nil),            // 43: cloche.v1.TerminalSize
	(*ConsoleExited)(nil),           // 44: cloche.v1.ConsoleExited
}
var file_cloche_proto_depIdxs = []int32{
	4,  // 0: cloche.v1.GetStatusResponse.step_executions:type_name -> cloche.v1.StepExecutionStatus
	15, // 1: cloche.v1.ListRunsResponse.runs:type_name -> cloche.v1.RunSummary
	15, // 2: cloche.v1.GetProjectInfoResponse.active_runs:type_name -> cloche.v1.RunSummary
	27, // 3: cloche.v1.ListTasksResponse.tasks:type_name -> cloche.v1.TaskSummary
	30, // 4: cloche.v1.GetTaskResponse.attempts:type_name -> cloche.v1.AttemptSummary
	38, // 5: cloche.v1.GetUsageResponse.summaries:type_name -> cloche.v1.UsageSummary
	41, // 6: cloche.v1.ConsoleInput.start:type_name -> cloche.v1.ConsoleStart
	43, // 7: cloche.v1.ConsoleInput.resize:type_name -> cloche.v1.TerminalSize
	42, // 8: cloche.v1.ConsoleOutput.started:type_name -> cloche.v1.ConsoleStarted
	44, // 9: cloche.v1.ConsoleOutput.exited:type_name -> cloche.v1.ConsoleExited
	0,  // 10: cloche.v1.ClocheService.RunWorkflow:input_type -> cloche.v1.RunWorkflowRequest
	2,  // 11: cloche.v1.ClocheService.GetStatus:input_type -> cloche.v1.GetStatusRequest
	5,  // 12: cloche.v1.ClocheService.StreamLogs:input_type -> cloche.v1.StreamLogsRequest
	7,  // 13: cloche.v1.ClocheService.StopRun:input_type -> cloche.v1.StopRunRequest
	13, // 14: cloche.v1.ClocheService.ListRuns:input_type -> cloche.v1.ListRunsRequest
	26, // 15: cloche.v1.ClocheService.ListTasks:input_type -> cloche.v1.ListTasksRequest
	29, // 16: cloche.v1.ClocheService.GetTask:input_type -> cloche.v1.GetTaskRequest
	32, // 17: cloche.v1.ClocheService.GetAttempt:input_type -> cloche.v1.GetAttemptRequest
	9,  // 18: cloche.v1.ClocheService.Shutdown:input_type -> cloche.v1.ShutdownRequest
	11, // 19: cloche.v1.ClocheService.DeleteContainer:input_type -> cloche.v1.DeleteContainerRequest
	16, // 20: cloche.v1.ClocheService.EnableLoop:input_type -> cloche.v1.EnableLoopRequest
	18, // 21: cloche.v1.ClocheService.DisableLoop:input_type -> cloche.v1.DisableLoopRequest
	20, // 22: cloche.v1.ClocheService.ResumeLoop:input_type -> cloche.v1.ResumeLoopRequest
	22, // 23: cloche.v1.ClocheService.GetProjectInfo:input_type -> cloche.v1.GetProjectInfoRequest
	24, // 24: cloche.v1.ClocheService.GetVersion:input_type -> cloche.v1.GetVersionRequest
	34, // 25: cloche.v1.ClocheService.Complete:input_type -> cloche.v1.CompleteRequest
	36, // 26: cloche.v1.ClocheService.GetUsage:input_type -> cloche.v1.GetUsageRequest
	39, // 27: cloche.v1.ClocheService.Console:input_type -> cloche.v1.ConsoleInput
	1,  // 28: cloche.v1.ClocheService.RunWorkflow:output_type -> cloche.v1.RunWorkflowResponse
	3,  // 29: cloche.v1.ClocheService.GetStatus:output_type -> cloche.v1.GetStatusResponse
	6,  // 30: cloche.v1.ClocheService.StreamLogs:output_type -> cloche.v1.LogEntry
	8,  // 31: cloche.v1.ClocheService.StopRun:output_type -> cloche.v1.StopRunResponse
	14, // 32: cloche.v1.ClocheService.ListRuns:output_type -> cloche.v1.ListRunsResponse
	28, // 33: cloche.v1.ClocheService.ListTasks:output_type -> cloche.v1.ListTasksResponse
	31, // 34: cloche.v1.ClocheService.GetTask:output_type -> cloche.v1.GetTaskResponse
	33, // 35: cloche.v1.ClocheService.GetAttempt:output_type -> cloche.v1.GetAttemptResponse
	10, // 36: cloche.v1.ClocheService.Shutdown:output_type -> cloche.v1.ShutdownResponse
	12, // 37: cloche.v1.ClocheService.DeleteContainer:output_type -> cloche.v1.DeleteContainerResponse
	17, // 38: cloche.v1.ClocheService.EnableLoop:output_type -> cloche.v1.EnableLoopResponse
	19, // 39: cloche.v1.ClocheService.DisableLoop:output_type -> cloche.v1.DisableLoopResponse
	21, // 40: cloche.v1.ClocheService.ResumeLoop:output_type -> cloche.v1.ResumeLoopResponse
	23, // 41: cloche.v1.ClocheService.GetProjectInfo:output_type -> cloche.v1.GetProjectInfoResponse
	25, // 42: cloche.v1.ClocheService.GetVersion:output_type -> cloche.v1.GetVersionResponse
	35, // 43: cloche.v1.ClocheService.Complete:output_type -> cloche.v1.CompleteResponse
	37, // 44: cloche.v1.ClocheService.GetUsage:output_type -> cloche.v1.GetUsageResponse
	40, // 45: cloche.v1.ClocheService.Console:output_type -> cloche.v1.ConsoleOutput
	28, // [28:46] is the sub-list for method output_type
	10, // [10:28] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_cloche_proto_init() }
func file_cloche_proto_init() {
	if File_cloche_proto != nil {
		return
	}
	file_cloche_proto_msgTypes[39].OneofWrappers = []any{
		(*ConsoleInput_Start)(nil),
		(*ConsoleInput_Stdin)(nil),
		(*ConsoleInput_Resize)(nil),
	}
	file_cloche_proto_msgTypes[40].OneofWrappers = []any{
		(*ConsoleOutput_Started)(nil),
		(*ConsoleOutput_Stdout)(nil),
		(*ConsoleOutput_Exited)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cloche_proto_rawDesc), len(file_cloche_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   45,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_cloche_proto_goTypes,
		DependencyIndexes: file_cloche_proto_depIdxs,
		MessageInfos:      file_cloche_proto_msgTypes,
	}.Build()
	File_cloche_proto = out.File
	file_cloche_proto_goTypes = nil
	file_cloche_proto_depIdxs = nil
}
