// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v5.29.3
// source: cloche.proto

package clochepb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ClocheService_RunWorkflow_FullMethodName     = "/cloche.v1.ClocheService/RunWorkflow"
	ClocheService_GetStatus_FullMethodName       = "/cloche.v1.ClocheService/GetStatus"
	ClocheService_StreamLogs_FullMethodName      = "/cloche.v1.ClocheService/StreamLogs"
	ClocheService_StopRun_FullMethodName         = "/cloche.v1.ClocheService/StopRun"
	ClocheService_ListRuns_FullMethodName        = "/cloche.v1.ClocheService/ListRuns"
	ClocheService_ListTasks_FullMethodName       = "/cloche.v1.ClocheService/ListTasks"
	ClocheService_GetTask_FullMethodName         = "/cloche.v1.ClocheService/GetTask"
	ClocheService_GetAttempt_FullMethodName      = "/cloche.v1.ClocheService/GetAttempt"
	ClocheService_Shutdown_FullMethodName        = "/cloche.v1.ClocheService/Shutdown"
	ClocheService_DeleteContainer_FullMethodName = "/cloche.v1.ClocheService/DeleteContainer"
	ClocheService_EnableLoop_FullMethodName      = "/cloche.v1.ClocheService/EnableLoop"
	ClocheService_DisableLoop_FullMethodName     = "/cloche.v1.ClocheService/DisableLoop"
	ClocheService_ResumeLoop_FullMethodName      = "/cloche.v1.ClocheService/ResumeLoop"
	ClocheService_GetProjectInfo_FullMethodName  = "/cloche.v1.ClocheService/GetProjectInfo"
	ClocheService_GetVersion_FullMethodName      = "/cloche.v1.ClocheService/GetVersion"
	ClocheService_Complete_FullMethodName        = "/cloche.v1.ClocheService/Complete"
	ClocheService_GetUsage_FullMethodName        = "/cloche.v1.ClocheService/GetUsage"
	ClocheService_Console_FullMethodName         = "/cloche.v1.ClocheService/Console"
)

// ClocheServiceClient is the client API for ClocheService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ClocheServiceClient interface {
	RunWorkflow(ctx context.Context, in *RunWorkflowRequest, opts ...grpc.CallOption) (*RunWorkflowResponse, error)
	GetStatus(ctx context.Context, in *GetStatusRequest, opts ...grpc.CallOption) (*GetStatusResponse, error)
	StreamLogs(ctx context.Context, in *StreamLogsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[LogEntry], error)
	StopRun(ctx context.Context, in *StopRunRequest, opts ...grpc.CallOption) (*StopRunResponse, error)
	ListRuns(ctx context.Context, in *ListRunsRequest, opts ...grpc.CallOption) (*ListRunsResponse, error)
	ListTasks(ctx context.Context, in *ListTasksRequest, opts ...grpc.CallOption) (*ListTasksResponse, error)
	GetTask(ctx context.Context, in *GetTaskRequest, opts ...grpc.CallOption) (*GetTaskResponse, error)
	GetAttempt(ctx context.Context, in *GetAttemptRequest, opts ...grpc.CallOption) (*GetAttemptResponse, error)
	Shutdown(ctx context.Context, in *ShutdownRequest, opts ...grpc.CallOption) (*ShutdownResponse, error)
	DeleteContainer(ctx context.Context, in *DeleteContainerRequest, opts ...grpc.CallOption) (*DeleteContainerResponse, error)
	EnableLoop(ctx context.Context, in *EnableLoopRequest, opts ...grpc.CallOption) (*EnableLoopResponse, error)
	DisableLoop(ctx context.Context, in *DisableLoopRequest, opts ...grpc.CallOption) (*DisableLoopResponse, error)
	ResumeLoop(ctx context.Context, in *ResumeLoopRequest, opts ...grpc.CallOption) (*ResumeLoopResponse, error)
	GetProjectInfo(ctx context.Context, in *GetProjectInfoRequest, opts ...grpc.CallOption) (*GetProjectInfoResponse, error)
	GetVersion(ctx context.Context, in *GetVersionRequest, opts ...grpc.CallOption) (*GetVersionResponse, error)
	// Complete returns shell completion candidates for the given partial command line.
	// Used by shell integration scripts to provide dynamic completions for task IDs,
	// attempt IDs, workflow names, and colon-delimited drill-down identifiers.
	Complete(ctx context.Context, in *CompleteRequest, opts ...grpc.CallOption) (*CompleteResponse, error)
	// GetUsage returns aggregated token usage statistics for a project or globally.
	GetUsage(ctx context.Context, in *GetUsageRequest, opts ...grpc.CallOption) (*GetUsageResponse, error)
	// Console starts an interactive terminal session inside a fresh container.
	// The first ConsoleInput must be a ConsoleStart message. The daemon responds
	// with ConsoleStarted, streams stdout bytes, and finally sends ConsoleExited.
	Console(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ConsoleInput, ConsoleOutput], error)
}

type clocheServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewClocheServiceClient(cc grpc.ClientConnInterface) ClocheServiceClient {
	return &clocheServiceClient{cc}
}

func (c *clocheServiceClient) RunWorkflow(ctx context.Context, in *RunWorkflowRequest, opts ...grpc.CallOption) (*RunWorkflowResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RunWorkflowResponse)
	err := c.cc.Invoke(ctx, ClocheService_RunWorkflow_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clocheServiceClient) GetStatus(ctx context.Context, in *GetStatusRequest, opts ...grpc.CallOption) (*GetStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetStatusResponse)
	err := c.cc.Invoke(ctx, ClocheService_GetStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clocheServiceClient) StreamLogs(ctx context.Context, in *StreamLogsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[LogEntry], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ClocheService_ServiceDesc.Streams[0], ClocheService_StreamLogs_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamLogsRequest, LogEntry]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ClocheService_StreamLogsClient = grpc.ServerStreamingClient[LogEntry]

func (c *clocheServiceClient) StopRun(ctx context.Context, in *StopRunRequest, opts ...grpc.CallOption) (*StopRunResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StopRunResponse)
	err := c.cc.Invoke(ctx, ClocheService_StopRun_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clocheServiceClient) ListRuns(ctx context.Context, in *ListRunsRequest, opts ...grpc.CallOption) (*ListRunsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListRunsResponse)
	err := c.cc.Invoke(ctx, ClocheService_ListRuns_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clocheServiceClient) ListTasks(ctx context.Context, in *ListTasksRequest, opts ...grpc.CallOption) (*ListTasksResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListTasksResponse)
	err := c.cc.Invoke(ctx, ClocheService_ListTasks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clocheServiceClient) GetTask(ctx context.Context, in *GetTaskRequest, opts ...grpc.CallOption) (*GetTaskResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTaskResponse)
	err := c.cc.Invoke(ctx, ClocheService_GetTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clocheServiceClient) GetAttempt(ctx context.Context, in *GetAttemptRequest, opts ...grpc.CallOption) (*GetAttemptResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAttemptResponse)
	err := c.cc.Invoke(ctx, ClocheService_GetAttempt_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clocheServiceClient) Shutdown(ctx context.Context, in *ShutdownRequest, opts ...grpc.CallOption) (*ShutdownResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ShutdownResponse)
	err := c.cc.Invoke(ctx, ClocheService_Shutdown_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clocheServiceClient) DeleteContainer(ctx context.Context, in *DeleteContainerRequest, opts ...grpc.CallOption) (*DeleteContainerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteContainerResponse)
	err := c.cc.Invoke(ctx, ClocheService_DeleteContainer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clocheServiceClient) EnableLoop(ctx context.Context, in *EnableLoopRequest, opts ...grpc.CallOption) (*EnableLoopResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EnableLoopResponse)
	err := c.cc.Invoke(ctx, ClocheService_EnableLoop_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clocheServiceClient) DisableLoop(ctx context.Context, in *DisableLoopRequest, opts ...grpc.CallOption) (*DisableLoopResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DisableLoopResponse)
	err := c.cc.Invoke(ctx, ClocheService_DisableLoop_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clocheServiceClient) ResumeLoop(ctx context.Context, in *ResumeLoopRequest, opts ...grpc.CallOption) (*ResumeLoopResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResumeLoopResponse)
	err := c.cc.Invoke(ctx, ClocheService_ResumeLoop_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clocheServiceClient) GetProjectInfo(ctx context.Context, in *GetProjectInfoRequest, opts ...grpc.CallOption) (*GetProjectInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetProjectInfoResponse)
	err := c.cc.Invoke(ctx, ClocheService_GetProjectInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clocheServiceClient) GetVersion(ctx context.Context, in *GetVersionRequest, opts ...grpc.CallOption) (*GetVersionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetVersionResponse)
	err := c.cc.Invoke(ctx, ClocheService_GetVersion_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clocheServiceClient) Complete(ctx context.Context, in *CompleteRequest, opts ...grpc.CallOption) (*CompleteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CompleteResponse)
	err := c.cc.Invoke(ctx, ClocheService_Complete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clocheServiceClient) GetUsage(ctx context.Context, in *GetUsageRequest, opts ...grpc.CallOption) (*GetUsageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUsageResponse)
	err := c.cc.Invoke(ctx, ClocheService_GetUsage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clocheServiceClient) Console(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ConsoleInput, ConsoleOutput], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ClocheService_ServiceDesc.Streams[1], ClocheService_Console_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ConsoleInput, ConsoleOutput]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ClocheService_ConsoleClient = grpc.BidiStreamingClient[ConsoleInput, ConsoleOutput]

// ClocheServiceServer is the server API for ClocheService service.
// All implementations must embed UnimplementedClocheServiceServer
// for forward compatibility.
type ClocheServiceServer interface {
	RunWorkflow(context.Context, *RunWorkflowRequest) (*RunWorkflowResponse, error)
	GetStatus(context.Context, *GetStatusRequest) (*GetStatusResponse, error)
	StreamLogs(*StreamLogsRequest, grpc.ServerStreamingServer[LogEntry]) error
	StopRun(context.Context, *StopRunRequest) (*StopRunResponse, error)
	ListRuns(context.Context, *ListRunsRequest) (*ListRunsResponse, error)
	ListTasks(context.Context, *ListTasksRequest) (*ListTasksResponse, error)
	GetTask(context.Context, *GetTaskRequest) (*GetTaskResponse, error)
	GetAttempt(context.Context, *GetAttemptRequest) (*GetAttemptResponse, error)
	Shutdown(context.Context, *ShutdownRequest) (*ShutdownResponse, error)
	DeleteContainer(context.Context, *DeleteContainerRequest) (*DeleteContainerResponse, error)
	EnableLoop(context.Context, *EnableLoopRequest) (*EnableLoopResponse, error)
	DisableLoop(context.Context, *DisableLoopRequest) (*DisableLoopResponse, error)
	ResumeLoop(context.Context, *ResumeLoopRequest) (*ResumeLoopResponse, error)
	GetProjectInfo(context.Context, *GetProjectInfoRequest) (*GetProjectInfoResponse, error)
	GetVersion(context.Context, *GetVersionRequest) (*GetVersionResponse, error)
	// Complete returns shell completion candidates for the given partial command line.
	// Used by shell integration scripts to provide dynamic completions for task IDs,
	// attempt IDs, workflow names, and colon-delimited drill-down identifiers.
	Complete(context.Context, *CompleteRequest) (*CompleteResponse, error)
	// GetUsage returns aggregated token usage statistics for a project or globally.
	GetUsage(context.Context, *GetUsageRequest) (*GetUsageResponse, error)
	// Console starts an interactive terminal session inside a fresh container.
	// The first ConsoleInput must be a ConsoleStart message. The daemon responds
	// with ConsoleStarted, streams stdout bytes, and finally sends ConsoleExited.
	Console(grpc.BidiStreamingServer[ConsoleInput, ConsoleOutput]) error
	mustEmbedUnimplementedClocheServiceServer()
}

// UnimplementedClocheServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedClocheServiceServer struct{}

func (UnimplementedClocheServiceServer) RunWorkflow(context.Context, *RunWorkflowRequest) (*RunWorkflowResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RunWorkflow not implemented")
}
func (UnimplementedClocheServiceServer) GetStatus(context.Context, *GetStatusRequest) (*GetStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetStatus not implemented")
}
func (UnimplementedClocheServiceServer) StreamLogs(*StreamLogsRequest, grpc.ServerStreamingServer[LogEntry]) error {
	return status.Error(codes.Unimplemented, "method StreamLogs not implemented")
}
func (UnimplementedClocheServiceServer) StopRun(context.Context, *StopRunRequest) (*StopRunResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StopRun not implemented")
}
func (UnimplementedClocheServiceServer) ListRuns(context.Context, *ListRunsRequest) (*ListRunsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListRuns not implemented")
}
func (UnimplementedClocheServiceServer) ListTasks(context.Context, *ListTasksRequest) (*ListTasksResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListTasks not implemented")
}
func (UnimplementedClocheServiceServer) GetTask(context.Context, *GetTaskRequest) (*GetTaskResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTask not implemented")
}
func (UnimplementedClocheServiceServer) GetAttempt(context.Context, *GetAttemptRequest) (*GetAttemptResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAttempt not implemented")
}
func (UnimplementedClocheServiceServer) Shutdown(context.Context, *ShutdownRequest) (*ShutdownResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Shutdown not implemented")
}
func (UnimplementedClocheServiceServer) DeleteContainer(context.Context, *DeleteContainerRequest) (*DeleteContainerResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteContainer not implemented")
}
func (UnimplementedClocheServiceServer) EnableLoop(context.Context, *EnableLoopRequest) (*EnableLoopResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method EnableLoop not implemented")
}
func (UnimplementedClocheServiceServer) DisableLoop(context.Context, *DisableLoopRequest) (*DisableLoopResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DisableLoop not implemented")
}
func (UnimplementedClocheServiceServer) ResumeLoop(context.Context, *ResumeLoopRequest) (*ResumeLoopResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ResumeLoop not implemented")
}
func (UnimplementedClocheServiceServer) GetProjectInfo(context.Context, *GetProjectInfoRequest) (*GetProjectInfoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetProjectInfo not implemented")
}
func (UnimplementedClocheServiceServer) GetVersion(context.Context, *GetVersionRequest) (*GetVersionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetVersion not implemented")
}
func (UnimplementedClocheServiceServer) Complete(context.Context, *CompleteRequest) (*CompleteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Complete not implemented")
}
func (UnimplementedClocheServiceServer) GetUsage(context.Context, *GetUsageRequest) (*GetUsageResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUsage not implemented")
}
func (UnimplementedClocheServiceServer) Console(grpc.BidiStreamingServer[ConsoleInput, ConsoleOutput]) error {
	return status.Error(codes.Unimplemented, "method Console not implemented")
}
func (UnimplementedClocheServiceServer) mustEmbedUnimplementedClocheServiceServer() {}
func (UnimplementedClocheServiceServer) testEmbeddedByValue()                       {}

// UnsafeClocheServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ClocheServiceServer will
// result in compilation errors.
type UnsafeClocheServiceServer interface {
	mustEmbedUnimplementedClocheServiceServer()
}

func RegisterClocheServiceServer(s grpc.ServiceRegistrar, srv ClocheServiceServer) {
	// If the following call panics, it indicates UnimplementedClocheServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ClocheService_ServiceDesc, srv)
}

func _ClocheService_RunWorkflow_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RunWorkflowRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClocheServiceServer).RunWorkflow(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClocheService_RunWorkflow_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClocheServiceServer).RunWorkflow(ctx, req.(*RunWorkflowRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClocheService_GetStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClocheServiceServer).GetStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClocheService_GetStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClocheServiceServer).GetStatus(ctx, req.(*GetStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClocheService_StreamLogs_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamLogsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ClocheServiceServer).StreamLogs(m, &grpc.GenericServerStream[StreamLogsRequest, LogEntry]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ClocheService_StreamLogsServer = grpc.ServerStreamingServer[LogEntry]

func _ClocheService_StopRun_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StopRunRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClocheServiceServer).StopRun(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClocheService_StopRun_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClocheServiceServer).StopRun(ctx, req.(*StopRunRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClocheService_ListRuns_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRunsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClocheServiceServer).ListRuns(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClocheService_ListRuns_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClocheServiceServer).ListRuns(ctx, req.(*ListRunsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClocheService_ListTasks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTasksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClocheServiceServer).ListTasks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClocheService_ListTasks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClocheServiceServer).ListTasks(ctx, req.(*ListTasksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClocheService_GetTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClocheServiceServer).GetTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClocheService_GetTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClocheServiceServer).GetTask(ctx, req.(*GetTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClocheService_GetAttempt_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAttemptRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClocheServiceServer).GetAttempt(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClocheService_GetAttempt_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClocheServiceServer).GetAttempt(ctx, req.(*GetAttemptRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClocheService_Shutdown_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ShutdownRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClocheServiceServer).Shutdown(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClocheService_Shutdown_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClocheServiceServer).Shutdown(ctx, req.(*ShutdownRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClocheService_DeleteContainer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteContainerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClocheServiceServer).DeleteContainer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClocheService_DeleteContainer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClocheServiceServer).DeleteContainer(ctx, req.(*DeleteContainerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClocheService_EnableLoop_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EnableLoopRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClocheServiceServer).EnableLoop(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClocheService_EnableLoop_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClocheServiceServer).EnableLoop(ctx, req.(*EnableLoopRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClocheService_DisableLoop_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DisableLoopRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClocheServiceServer).DisableLoop(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClocheService_DisableLoop_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClocheServiceServer).DisableLoop(ctx, req.(*DisableLoopRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClocheService_ResumeLoop_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResumeLoopRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClocheServiceServer).ResumeLoop(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClocheService_ResumeLoop_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClocheServiceServer).ResumeLoop(ctx, req.(*ResumeLoopRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClocheService_GetProjectInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProjectInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClocheServiceServer).GetProjectInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClocheService_GetProjectInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClocheServiceServer).GetProjectInfo(ctx, req.(*GetProjectInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClocheService_GetVersion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetVersionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClocheServiceServer).GetVersion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClocheService_GetVersion_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClocheServiceServer).GetVersion(ctx, req.(*GetVersionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClocheService_Complete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CompleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClocheServiceServer).Complete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClocheService_Complete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClocheServiceServer).Complete(ctx, req.(*CompleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClocheService_GetUsage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUsageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClocheServiceServer).GetUsage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClocheService_GetUsage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClocheServiceServer).GetUsage(ctx, req.(*GetUsageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClocheService_Console_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ClocheServiceServer).Console(&grpc.GenericServerStream[ConsoleInput, ConsoleOutput]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ClocheService_ConsoleServer = grpc.BidiStreamingServer[ConsoleInput, ConsoleOutput]

// ClocheService_ServiceDesc is the grpc.ServiceDesc for ClocheService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ClocheService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "cloche.v1.ClocheService",
	HandlerType: (*ClocheServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RunWorkflow",
			Handler:    _ClocheService_RunWorkflow_Handler,
		},
		{
			MethodName: "GetStatus",
			Handler:    _ClocheService_GetStatus_Handler,
		},
		{
			MethodName: "StopRun",
			Handler:    _ClocheService_StopRun_Handler,
		},
		{
			MethodName: "ListRuns",
			Handler:    _ClocheService_ListRuns_Handler,
		},
		{
			MethodName: "ListTasks",
			Handler:    _ClocheService_ListTasks_Handler,
		},
		{
			MethodName: "GetTask",
			Handler:    _ClocheService_GetTask_Handler,
		},
		{
			MethodName: "GetAttempt",
			Handler:    _ClocheService_GetAttempt_Handler,
		},
		{
			MethodName: "Shutdown",
			Handler:    _ClocheService_Shutdown_Handler,
		},
		{
			MethodName: "DeleteContainer",
			Handler:    _ClocheService_DeleteContainer_Handler,
		},
		{
			MethodName: "EnableLoop",
			Handler:    _ClocheService_EnableLoop_Handler,
		},
		{
			MethodName: "DisableLoop",
			Handler:    _ClocheService_DisableLoop_Handler,
		},
		{
			MethodName: "ResumeLoop",
			Handler:    _ClocheService_ResumeLoop_Handler,
		},
		{
			MethodName: "GetProjectInfo",
			Handler:    _ClocheService_GetProjectInfo_Handler,
		},
		{
			MethodName: "GetVersion",
			Handler:    _ClocheService_GetVersion_Handler,
		},
		{
			MethodName: "Complete",
			Handler:    _ClocheService_Complete_Handler,
		},
		{
			MethodName: "GetUsage",
			Handler:    _ClocheService_GetUsage_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamLogs",
			Handler:       _ClocheService_StreamLogs_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "Console",
			Handler:       _ClocheService_Console_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "cloche.proto",
}
