// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: cloche.proto

package clochepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RunWorkflowRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkflowName  string                 `protobuf:"bytes,1,opt,name=workflow_name,json=workflowName,proto3" json:"workflow_name,omitempty"`
	ProjectDir    string                 `protobuf:"bytes,2,opt,name=project_dir,json=projectDir,proto3" json:"project_dir,omitempty"`
	Image         string                 `protobuf:"bytes,3,opt,name=image,proto3" json:"image,omitempty"`
	Prompt        string                 `protobuf:"bytes,4,opt,name=prompt,proto3" json:"prompt,omitempty"`
	KeepContainer bool                   `protobuf:"varint,5,opt,name=keep_container,json=keepContainer,proto3" json:"keep_container,omitempty"`
	Title         string                 `protobuf:"bytes,6,opt,name=title,proto3" json:"title,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunWorkflowRequest) Reset() {
	*x = RunWorkflowRequest{}
	mi := &file_cloche_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunWorkflowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunWorkflowRequest) ProtoMessage() {}

func (x *RunWorkflowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cloche_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunWorkflowRequest.ProtoReflect.Descriptor instead.
func (*RunWorkflowRequest) Descriptor() ([]byte, []int) {
	return file_cloche_proto_rawDescGZIP(), []int{0}
}

func (x *RunWorkflowRequest) GetWorkflowName() string {
	if x != nil {
		return x.WorkflowName
	}
	return ""
}

func (x *RunWorkflowRequest) GetProjectDir() string {
	if x != nil {
		return x.ProjectDir
	}
	return ""
}

func (x *RunWorkflowRequest) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *RunWorkflowRequest) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

func (x *RunWorkflowRequest) GetKeepContainer() bool {
	if x != nil {
		return x.KeepContainer
	}
	return false
}

func (x *RunWorkflowRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

type RunWorkflowResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RunId         string                 `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunWorkflowResponse) Reset() {
	*x = RunWorkflowResponse{}
	mi := &file_cloche_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunWorkflowResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunWorkflowResponse) ProtoMessage() {}

func (x *RunWorkflowResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cloche_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunWorkflowResponse.ProtoReflect.Descriptor instead.
func (*RunWorkflowResponse) Descriptor() ([]byte, []int) {
	return file_cloche_proto_rawDescGZIP(), []int{1}
}

func (x *RunWorkflowResponse) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

type GetStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RunId         string                 `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatusRequest) Reset() {
	*x = GetStatusRequest{}
	mi := &file_cloche_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatusRequest) ProtoMessage() {}

func (x *GetStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cloche_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatusRequest.ProtoReflect.Descriptor instead.
func (*GetStatusRequest) Descriptor() ([]byte, []int) {
	return file_cloche_proto_rawDescGZIP(), []int{2}
}

func (x *GetStatusRequest) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

type GetStatusResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	RunId              string                 `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	WorkflowName       string                 `protobuf:"bytes,2,opt,name=workflow_name,json=workflowName,proto3" json:"workflow_name,omitempty"`
	State              string                 `protobuf:"bytes,3,opt,name=state,proto3" json:"state,omitempty"`
	CurrentStep        string                 `protobuf:"bytes,4,opt,name=current_step,json=currentStep,proto3" json:"current_step,omitempty"`
	StepExecutions     []*StepExecutionStatus `protobuf:"bytes,5,rep,name=step_executions,json=stepExecutions,proto3" json:"step_executions,omitempty"`
	ErrorMessage       string                 `protobuf:"bytes,6,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	ContainerId        string                 `protobuf:"bytes,7,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"`
	ContainerAlive     bool                   `protobuf:"varint,8,opt,name=container_alive,json=containerAlive,proto3" json:"container_alive,omitempty"`
	ContainerDeadSince string                 `protobuf:"bytes,9,opt,name=container_dead_since,json=containerDeadSince,proto3" json:"container_dead_since,omitempty"`
	Title              string                 `protobuf:"bytes,10,opt,name=title,proto3" json:"title,omitempty"`
	IsHost             bool                   `protobuf:"varint,11,opt,name=is_host,json=isHost,proto3" json:"is_host,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *GetStatusResponse) Reset() {
	*x = GetStatusResponse{}
	mi := &file_cloche_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatusResponse) ProtoMessage() {}

func (x *GetStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cloche_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatusResponse.ProtoReflect.Descriptor instead.
func (*GetStatusResponse) Descriptor() ([]byte, []int) {
	return file_cloche_proto_rawDescGZIP(), []int{3}
}

func (x *GetStatusResponse) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *GetStatusResponse) GetWorkflowName() string {
	if x != nil {
		return x.WorkflowName
	}
	return ""
}

func (x *GetStatusResponse) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *GetStatusResponse) GetCurrentStep() string {
	if x != nil {
		return x.CurrentStep
	}
	return ""
}

func (x *GetStatusResponse) GetStepExecutions() []*StepExecutionStatus {
	if x != nil {
		return x.StepExecutions
	}
	return nil
}

func (x *GetStatusResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *GetStatusResponse) GetContainerId() string {
	if x != nil {
		return x.ContainerId
	}
	return ""
}

func (x *GetStatusResponse) GetContainerAlive() bool {
	if x != nil {
		return x.ContainerAlive
	}
	return false
}

func (x *GetStatusResponse) GetContainerDeadSince() string {
	if x != nil {
		return x.ContainerDeadSince
	}
	return ""
}

func (x *GetStatusResponse) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *GetStatusResponse) GetIsHost() bool {
	if x != nil {
		return x.IsHost
	}
	return false
}

type StepExecutionStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StepName      string                 `protobuf:"bytes,1,opt,name=step_name,json=stepName,proto3" json:"step_name,omitempty"`
	Result        string                 `protobuf:"bytes,2,opt,name=result,proto3" json:"result,omitempty"`
	StartedAt     string                 `protobuf:"bytes,3,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	CompletedAt   string                 `protobuf:"bytes,4,opt,name=completed_at,json=completedAt,proto3" json:"completed_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StepExecutionStatus) Reset() {
	*x = StepExecutionStatus{}
	mi := &file_cloche_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StepExecutionStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StepExecutionStatus) ProtoMessage() {}

func (x *StepExecutionStatus) ProtoReflect() protoreflect.Message {
	mi := &file_cloche_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StepExecutionStatus.ProtoReflect.Descriptor instead.
func (*StepExecutionStatus) Descriptor() ([]byte, []int) {
	return file_cloche_proto_rawDescGZIP(), []int{4}
}

func (x *StepExecutionStatus) GetStepName() string {
	if x != nil {
		return x.StepName
	}
	return ""
}

func (x *StepExecutionStatus) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

func (x *StepExecutionStatus) GetStartedAt() string {
	if x != nil {
		return x.StartedAt
	}
	return ""
}

func (x *StepExecutionStatus) GetCompletedAt() string {
	if x != nil {
		return x.CompletedAt
	}
	return ""
}

type StreamLogsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RunId         string                 `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	StepName      string                 `protobuf:"bytes,2,opt,name=step_name,json=stepName,proto3" json:"step_name,omitempty"`
	LogType       string                 `protobuf:"bytes,3,opt,name=log_type,json=logType,proto3" json:"log_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamLogsRequest) Reset() {
	*x = StreamLogsRequest{}
	mi := &file_cloche_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamLogsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamLogsRequest) ProtoMessage() {}

func (x *StreamLogsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cloche_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamLogsRequest.ProtoReflect.Descriptor instead.
func (*StreamLogsRequest) Descriptor() ([]byte, []int) {
	return file_cloche_proto_rawDescGZIP(), []int{5}
}

func (x *StreamLogsRequest) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *StreamLogsRequest) GetStepName() string {
	if x != nil {
		return x.StepName
	}
	return ""
}

func (x *StreamLogsRequest) GetLogType() string {
	if x != nil {
		return x.LogType
	}
	return ""
}

type LogEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	StepName      string                 `protobuf:"bytes,2,opt,name=step_name,json=stepName,proto3" json:"step_name,omitempty"`
	Result        string                 `protobuf:"bytes,3,opt,name=result,proto3" json:"result,omitempty"`
	Message       string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	Timestamp     string                 `protobuf:"bytes,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogEntry) Reset() {
	*x = LogEntry{}
	mi := &file_cloche_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogEntry) ProtoMessage() {}

func (x *LogEntry) ProtoReflect() protoreflect.Message {
	mi := &file_cloche_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogEntry.ProtoReflect.Descriptor instead.
func (*LogEntry) Descriptor() ([]byte, []int) {
	return file_cloche_proto_rawDescGZIP(), []int{6}
}

func (x *LogEntry) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *LogEntry) GetStepName() string {
	if x != nil {
		return x.StepName
	}
	return ""
}

func (x *LogEntry) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

func (x *LogEntry) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *LogEntry) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

type StopRunRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RunId         string                 `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopRunRequest) Reset() {
	*x = StopRunRequest{}
	mi := &file_cloche_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopRunRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopRunRequest) ProtoMessage() {}

func (x *StopRunRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cloche_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopRunRequest.ProtoReflect.Descriptor instead.
func (*StopRunRequest) Descriptor() ([]byte, []int) {
	return file_cloche_proto_rawDescGZIP(), []int{7}
}

func (x *StopRunRequest) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

type StopRunResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopRunResponse) Reset() {
	*x = StopRunResponse{}
	mi := &file_cloche_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopRunResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopRunResponse) ProtoMessage() {}

func (x *StopRunResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cloche_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopRunResponse.ProtoReflect.Descriptor instead.
func (*StopRunResponse) Descriptor() ([]byte, []int) {
	return file_cloche_proto_rawDescGZIP(), []int{8}
}

type ShutdownRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShutdownRequest) Reset() {
	*x = ShutdownRequest{}
	mi := &file_cloche_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShutdownRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShutdownRequest) ProtoMessage() {}

func (x *ShutdownRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cloche_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShutdownRequest.ProtoReflect.Descriptor instead.
func (*ShutdownRequest) Descriptor() ([]byte, []int) {
	return file_cloche_proto_rawDescGZIP(), []int{9}
}

type ShutdownResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShutdownResponse) Reset() {
	*x = ShutdownResponse{}
	mi := &file_cloche_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShutdownResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShutdownResponse) ProtoMessage() {}

func (x *ShutdownResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cloche_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShutdownResponse.ProtoReflect.Descriptor instead.
func (*ShutdownResponse) Descriptor() ([]byte, []int) {
	return file_cloche_proto_rawDescGZIP(), []int{10}
}

type DeleteContainerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteContainerRequest) Reset() {
	*x = DeleteContainerRequest{}
	mi := &file_cloche_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteContainerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteContainerRequest) ProtoMessage() {}

func (x *DeleteContainerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cloche_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteContainerRequest.ProtoReflect.Descriptor instead.
func (*DeleteContainerRequest) Descriptor() ([]byte, []int) {
	return file_cloche_proto_rawDescGZIP(), []int{11}
}

func (x *DeleteContainerRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteContainerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteContainerResponse) Reset() {
	*x = DeleteContainerResponse{}
	mi := &file_cloche_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteContainerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteContainerResponse) ProtoMessage() {}

func (x *DeleteContainerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cloche_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteContainerResponse.ProtoReflect.Descriptor instead.
func (*DeleteContainerResponse) Descriptor() ([]byte, []int) {
	return file_cloche_proto_rawDescGZIP(), []int{12}
}

type OrchestrateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectDir    string                 `protobuf:"bytes,1,opt,name=project_dir,json=projectDir,proto3" json:"project_dir,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrchestrateRequest) Reset() {
	*x = OrchestrateRequest{}
	mi := &file_cloche_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrchestrateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrchestrateRequest) ProtoMessage() {}

func (x *OrchestrateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cloche_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrchestrateRequest.ProtoReflect.Descriptor instead.
func (*OrchestrateRequest) Descriptor() ([]byte, []int) {
	return file_cloche_proto_rawDescGZIP(), []int{13}
}

func (x *OrchestrateRequest) GetProjectDir() string {
	if x != nil {
		return x.ProjectDir
	}
	return ""
}

type OrchestrateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RunId         string                 `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrchestrateResponse) Reset() {
	*x = OrchestrateResponse{}
	mi := &file_cloche_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrchestrateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrchestrateResponse) ProtoMessage() {}

func (x *OrchestrateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cloche_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrchestrateResponse.ProtoReflect.Descriptor instead.
func (*OrchestrateResponse) Descriptor() ([]byte, []int) {
	return file_cloche_proto_rawDescGZIP(), []int{14}
}

func (x *OrchestrateResponse) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

type ListRunsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	All           bool                   `protobuf:"varint,1,opt,name=all,proto3" json:"all,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRunsRequest) Reset() {
	*x = ListRunsRequest{}
	mi := &file_cloche_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRunsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRunsRequest) ProtoMessage() {}

func (x *ListRunsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cloche_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRunsRequest.ProtoReflect.Descriptor instead.
func (*ListRunsRequest) Descriptor() ([]byte, []int) {
	return file_cloche_proto_rawDescGZIP(), []int{15}
}

func (x *ListRunsRequest) GetAll() bool {
	if x != nil {
		return x.All
	}
	return false
}

type ListRunsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Runs          []*RunSummary          `protobuf:"bytes,1,rep,name=runs,proto3" json:"runs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRunsResponse) Reset() {
	*x = ListRunsResponse{}
	mi := &file_cloche_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRunsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRunsResponse) ProtoMessage() {}

func (x *ListRunsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cloche_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRunsResponse.ProtoReflect.Descriptor instead.
func (*ListRunsResponse) Descriptor() ([]byte, []int) {
	return file_cloche_proto_rawDescGZIP(), []int{16}
}

func (x *ListRunsResponse) GetRuns() []*RunSummary {
	if x != nil {
		return x.Runs
	}
	return nil
}

type RunSummary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RunId         string                 `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	WorkflowName  string                 `protobuf:"bytes,2,opt,name=workflow_name,json=workflowName,proto3" json:"workflow_name,omitempty"`
	State         string                 `protobuf:"bytes,3,opt,name=state,proto3" json:"state,omitempty"`
	StartedAt     string                 `protobuf:"bytes,4,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,5,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	ContainerId   string                 `protobuf:"bytes,6,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"`
	Title         string                 `protobuf:"bytes,7,opt,name=title,proto3" json:"title,omitempty"`
	IsHost        bool                   `protobuf:"varint,8,opt,name=is_host,json=isHost,proto3" json:"is_host,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunSummary) Reset() {
	*x = RunSummary{}
	mi := &file_cloche_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunSummary) ProtoMessage() {}

func (x *RunSummary) ProtoReflect() protoreflect.Message {
	mi := &file_cloche_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunSummary.ProtoReflect.Descriptor instead.
func (*RunSummary) Descriptor() ([]byte, []int) {
	return file_cloche_proto_rawDescGZIP(), []int{17}
}

func (x *RunSummary) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *RunSummary) GetWorkflowName() string {
	if x != nil {
		return x.WorkflowName
	}
	return ""
}

func (x *RunSummary) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *RunSummary) GetStartedAt() string {
	if x != nil {
		return x.StartedAt
	}
	return ""
}

func (x *RunSummary) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *RunSummary) GetContainerId() string {
	if x != nil {
		return x.ContainerId
	}
	return ""
}

func (x *RunSummary) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *RunSummary) GetIsHost() bool {
	if x != nil {
		return x.IsHost
	}
	return false
}

type EnableLoopRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectDir    string                 `protobuf:"bytes,1,opt,name=project_dir,json=projectDir,proto3" json:"project_dir,omitempty"`
	MaxConcurrent int32                  `protobuf:"varint,2,opt,name=max_concurrent,json=maxConcurrent,proto3" json:"max_concurrent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnableLoopRequest) Reset() {
	*x = EnableLoopRequest{}
	mi := &file_cloche_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnableLoopRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnableLoopRequest) ProtoMessage() {}

func (x *EnableLoopRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cloche_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnableLoopRequest.ProtoReflect.Descriptor instead.
func (*EnableLoopRequest) Descriptor() ([]byte, []int) {
	return file_cloche_proto_rawDescGZIP(), []int{18}
}

func (x *EnableLoopRequest) GetProjectDir() string {
	if x != nil {
		return x.ProjectDir
	}
	return ""
}

func (x *EnableLoopRequest) GetMaxConcurrent() int32 {
	if x != nil {
		return x.MaxConcurrent
	}
	return 0
}

type EnableLoopResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnableLoopResponse) Reset() {
	*x = EnableLoopResponse{}
	mi := &file_cloche_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnableLoopResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnableLoopResponse) ProtoMessage() {}

func (x *EnableLoopResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cloche_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnableLoopResponse.ProtoReflect.Descriptor instead.
func (*EnableLoopResponse) Descriptor() ([]byte, []int) {
	return file_cloche_proto_rawDescGZIP(), []int{19}
}

type DisableLoopRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectDir    string                 `protobuf:"bytes,1,opt,name=project_dir,json=projectDir,proto3" json:"project_dir,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DisableLoopRequest) Reset() {
	*x = DisableLoopRequest{}
	mi := &file_cloche_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DisableLoopRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisableLoopRequest) ProtoMessage() {}

func (x *DisableLoopRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cloche_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisableLoopRequest.ProtoReflect.Descriptor instead.
func (*DisableLoopRequest) Descriptor() ([]byte, []int) {
	return file_cloche_proto_rawDescGZIP(), []int{20}
}

func (x *DisableLoopRequest) GetProjectDir() string {
	if x != nil {
		return x.ProjectDir
	}
	return ""
}

type DisableLoopResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DisableLoopResponse) Reset() {
	*x = DisableLoopResponse{}
	mi := &file_cloche_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DisableLoopResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisableLoopResponse) ProtoMessage() {}

func (x *DisableLoopResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cloche_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisableLoopResponse.ProtoReflect.Descriptor instead.
func (*DisableLoopResponse) Descriptor() ([]byte, []int) {
	return file_cloche_proto_rawDescGZIP(), []int{21}
}

var File_cloche_proto protoreflect.FileDescriptor

const file_cloche_proto_rawDesc = "" +
	"\n" +
	"\fcloche.proto\x12\tcloche.v1\"\xc5\x01\n" +
	"\x12RunWorkflowRequest\x12#\n" +
	"\rworkflow_name\x18\x01 \x01(\tR\fworkflowName\x12\x1f\n" +
	"\vproject_dir\x18\x02 \x01(\tR\n" +
	"projectDir\x12\x14\n" +
	"\x05image\x18\x03 \x01(\tR\x05image\x12\x16\n" +
	"\x06prompt\x18\x04 \x01(\tR\x06prompt\x12%\n" +
	"\x0ekeep_container\x18\x05 \x01(\bR\rkeepContainer\x12\x14\n" +
	"\x05title\x18\x06 \x01(\tR\x05title\",\n" +
	"\x13RunWorkflowResponse\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\")\n" +
	"\x10GetStatusRequest\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\"\xa3\x03\n" +
	"\x11GetStatusResponse\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\x12#\n" +
	"\rworkflow_name\x18\x02 \x01(\tR\fworkflowName\x12\x14\n" +
	"\x05state\x18\x03 \x01(\tR\x05state\x12!\n" +
	"\fcurrent_step\x18\x04 \x01(\tR\vcurrentStep\x12G\n" +
	"\x0fstep_executions\x18\x05 \x03(\v2\x1e.cloche.v1.StepExecutionStatusR\x0estepExecutions\x12#\n" +
	"\rerror_message\x18\x06 \x01(\tR\ferrorMessage\x12!\n" +
	"\fcontainer_id\x18\a \x01(\tR\vcontainerId\x12'\n" +
	"\x0fcontainer_alive\x18\b \x01(\bR\x0econtainerAlive\x120\n" +
	"\x14container_dead_since\x18\t \x01(\tR\x12containerDeadSince\x12\x14\n" +
	"\x05title\x18\n" +
	" \x01(\tR\x05title\x12\x17\n" +
	"\ais_host\x18\v \x01(\bR\x06isHost\"\x8c\x01\n" +
	"\x13StepExecutionStatus\x12\x1b\n" +
	"\tstep_name\x18\x01 \x01(\tR\bstepName\x12\x16\n" +
	"\x06result\x18\x02 \x01(\tR\x06result\x12\x1d\n" +
	"\n" +
	"started_at\x18\x03 \x01(\tR\tstartedAt\x12!\n" +
	"\fcompleted_at\x18\x04 \x01(\tR\vcompletedAt\"b\n" +
	"\x11StreamLogsRequest\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\x12\x1b\n" +
	"\tstep_name\x18\x02 \x01(\tR\bstepName\x12\x19\n" +
	"\blog_type\x18\x03 \x01(\tR\alogType\"\x8b\x01\n" +
	"\bLogEntry\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x1b\n" +
	"\tstep_name\x18\x02 \x01(\tR\bstepName\x12\x16\n" +
	"\x06result\x18\x03 \x01(\tR\x06result\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\x12\x1c\n" +
	"\ttimestamp\x18\x05 \x01(\tR\ttimestamp\"'\n" +
	"\x0eStopRunRequest\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\"\x11\n" +
	"\x0fStopRunResponse\"\x11\n" +
	"\x0fShutdownRequest\"\x12\n" +
	"\x10ShutdownResponse\"(\n" +
	"\x16DeleteContainerRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x19\n" +
	"\x17DeleteContainerResponse\"5\n" +
	"\x12OrchestrateRequest\x12\x1f\n" +
	"\vproject_dir\x18\x01 \x01(\tR\n" +
	"projectDir\",\n" +
	"\x13OrchestrateResponse\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\"#\n" +
	"\x0fListRunsRequest\x12\x10\n" +
	"\x03all\x18\x01 \x01(\bR\x03all\"=\n" +
	"\x10ListRunsResponse\x12)\n" +
	"\x04runs\x18\x01 \x03(\v2\x15.cloche.v1.RunSummaryR\x04runs\"\xf4\x01\n" +
	"\n" +
	"RunSummary\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\x12#\n" +
	"\rworkflow_name\x18\x02 \x01(\tR\fworkflowName\x12\x14\n" +
	"\x05state\x18\x03 \x01(\tR\x05state\x12\x1d\n" +
	"\n" +
	"started_at\x18\x04 \x01(\tR\tstartedAt\x12#\n" +
	"\rerror_message\x18\x05 \x01(\tR\ferrorMessage\x12!\n" +
	"\fcontainer_id\x18\x06 \x01(\tR\vcontainerId\x12\x14\n" +
	"\x05title\x18\a \x01(\tR\x05title\x12\x17\n" +
	"\ais_host\x18\b \x01(\bR\x06isHost\"[\n" +
	"\x11EnableLoopRequest\x12\x1f\n" +
	"\vproject_dir\x18\x01 \x01(\tR\n" +
	"projectDir\x12%\n" +
	"\x0emax_concurrent\x18\x02 \x01(\x05R\rmaxConcurrent\"\x14\n" +
	"\x12EnableLoopResponse\"5\n" +
	"\x12DisableLoopRequest\x12\x1f\n" +
	"\vproject_dir\x18\x01 \x01(\tR\n" +
	"projectDir\"\x15\n" +
	"\x13DisableLoopResponse2\xf5\x05\n" +
	"\rClocheService\x12L\n" +
	"\vRunWorkflow\x12\x1d.cloche.v1.RunWorkflowRequest\x1a\x1e.cloche.v1.RunWorkflowResponse\x12F\n" +
	"\tGetStatus\x12\x1b.cloche.v1.GetStatusRequest\x1a\x1c.cloche.v1.GetStatusResponse\x12A\n" +
	"\n" +
	"StreamLogs\x12\x1c.cloche.v1.StreamLogsRequest\x1a\x13.cloche.v1.LogEntry0\x01\x12@\n" +
	"\aStopRun\x12\x19.cloche.v1.StopRunRequest\x1a\x1a.cloche.v1.StopRunResponse\x12C\n" +
	"\bListRuns\x12\x1a.cloche.v1.ListRunsRequest\x1a\x1b.cloche.v1.ListRunsResponse\x12C\n" +
	"\bShutdown\x12\x1a.cloche.v1.ShutdownRequest\x1a\x1b.cloche.v1.ShutdownResponse\x12X\n" +
	"\x0fDeleteContainer\x12!.cloche.v1.DeleteContainerRequest\x1a\".cloche.v1.DeleteContainerResponse\x12L\n" +
	"\vOrchestrate\x12\x1d.cloche.v1.OrchestrateRequest\x1a\x1e.cloche.v1.OrchestrateResponse\x12I\n" +
	"\n" +
	"EnableLoop\x12\x1c.cloche.v1.EnableLoopRequest\x1a\x1d.cloche.v1.EnableLoopResponse\x12L\n" +
	"\vDisableLoop\x12\x1d.cloche.v1.DisableLoopRequest\x1a\x1e.cloche.v1.DisableLoopResponseB+Z)github.com/cloche-dev/cloche/api/clochepbb\x06proto3"

var (
	file_cloche_proto_rawDescOnce sync.Once
	file_cloche_proto_rawDescData []byte
)

func file_cloche_proto_rawDescGZIP() []byte {
	file_cloche_proto_rawDescOnce.Do(func() {
		file_cloche_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cloche_proto_rawDesc), len(file_cloche_proto_rawDesc)))
	})
	return file_cloche_proto_rawDescData
}

var file_cloche_proto_msgTypes = make([]protoimpl.MessageInfo, 22)
var file_cloche_proto_goTypes = []any{
	(*RunWorkflowRequest)(nil),      // 0: cloche.v1.RunWorkflowRequest
	(*RunWorkflowResponse)(nil),     // 1: cloche.v1.RunWorkflowResponse
	(*GetStatusRequest)(nil),        // 2: cloche.v1.GetStatusRequest
	(*GetStatusResponse)(nil),       // 3: cloche.v1.GetStatusResponse
	(*StepExecutionStatus)(nil),     // 4: cloche.v1.StepExecutionStatus
	(*StreamLogsRequest)(nil),       // 5: cloche.v1.StreamLogsRequest
	(*LogEntry)(nil),                // 6: cloche.v1.LogEntry
	(*StopRunRequest)(nil),          // 7: cloche.v1.StopRunRequest
	(*StopRunResponse)(nil),         // 8: cloche.v1.StopRunResponse
	(*ShutdownRequest)(nil),         // 9: cloche.v1.ShutdownRequest
	(*ShutdownResponse)(nil),        // 10: cloche.v1.ShutdownResponse
	(*DeleteContainerRequest)(nil),  // 11: cloche.v1.DeleteContainerRequest
	(*DeleteContainerResponse)(nil), // 12: cloche.v1.DeleteContainerResponse
	(*OrchestrateRequest)(nil),      // 13: cloche.v1.OrchestrateRequest
	(*OrchestrateResponse)(nil),     // 14: cloche.v1.OrchestrateResponse
	(*ListRunsRequest)(nil),         // 15: cloche.v1.ListRunsRequest
	(*ListRunsResponse)(nil),        // 16: cloche.v1.ListRunsResponse
	(*RunSummary)(nil),              // 17: cloche.v1.RunSummary
	(*EnableLoopRequest)(nil),       // 18: cloche.v1.EnableLoopRequest
	(*EnableLoopResponse)(nil),      // 19: cloche.v1.EnableLoopResponse
	(*DisableLoopRequest)(nil),      // 20: cloche.v1.DisableLoopRequest
	(*DisableLoopResponse)(nil),     // 21: cloche.v1.DisableLoopResponse
}
var file_cloche_proto_depIdxs = []int32{
	4,  // 0: cloche.v1.GetStatusResponse.step_executions:type_name -> cloche.v1.StepExecutionStatus
	17, // 1: cloche.v1.ListRunsResponse.runs:type_name -> cloche.v1.RunSummary
	0,  // 2: cloche.v1.ClocheService.RunWorkflow:input_type -> cloche.v1.RunWorkflowRequest
	2,  // 3: cloche.v1.ClocheService.GetStatus:input_type -> cloche.v1.GetStatusRequest
	5,  // 4: cloche.v1.ClocheService.StreamLogs:input_type -> cloche.v1.StreamLogsRequest
	7,  // 5: cloche.v1.ClocheService.StopRun:input_type -> cloche.v1.StopRunRequest
	15, // 6: cloche.v1.ClocheService.ListRuns:input_type -> cloche.v1.ListRunsRequest
	9,  // 7: cloche.v1.ClocheService.Shutdown:input_type -> cloche.v1.ShutdownRequest
	11, // 8: cloche.v1.ClocheService.DeleteContainer:input_type -> cloche.v1.DeleteContainerRequest
	13, // 9: cloche.v1.ClocheService.Orchestrate:input_type -> cloche.v1.OrchestrateRequest
	18, // 10: cloche.v1.ClocheService.EnableLoop:input_type -> cloche.v1.EnableLoopRequest
	20, // 11: cloche.v1.ClocheService.DisableLoop:input_type -> cloche.v1.DisableLoopRequest
	1,  // 12: cloche.v1.ClocheService.RunWorkflow:output_type -> cloche.v1.RunWorkflowResponse
	3,  // 13: cloche.v1.ClocheService.GetStatus:output_type -> cloche.v1.GetStatusResponse
	6,  // 14: cloche.v1.ClocheService.StreamLogs:output_type -> cloche.v1.LogEntry
	8,  // 15: cloche.v1.ClocheService.StopRun:output_type -> cloche.v1.StopRunResponse
	16, // 16: cloche.v1.ClocheService.ListRuns:output_type -> cloche.v1.ListRunsResponse
	10, // 17: cloche.v1.ClocheService.Shutdown:output_type -> cloche.v1.ShutdownResponse
	12, // 18: cloche.v1.ClocheService.DeleteContainer:output_type -> cloche.v1.DeleteContainerResponse
	14, // 19: cloche.v1.ClocheService.Orchestrate:output_type -> cloche.v1.OrchestrateResponse
	19, // 20: cloche.v1.ClocheService.EnableLoop:output_type -> cloche.v1.EnableLoopResponse
	21, // 21: cloche.v1.ClocheService.DisableLoop:output_type -> cloche.v1.DisableLoopResponse
	12, // [12:22] is the sub-list for method output_type
	2,  // [2:12] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_cloche_proto_init() }
func file_cloche_proto_init() {
	if File_cloche_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cloche_proto_rawDesc), len(file_cloche_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   22,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_cloche_proto_goTypes,
		DependencyIndexes: file_cloche_proto_depIdxs,
		MessageInfos:      file_cloche_proto_msgTypes,
	}.Build()
	File_cloche_proto = out.File
	file_cloche_proto_goTypes = nil
	file_cloche_proto_depIdxs = nil
}
