// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v5.29.3
// source: cloche.proto

package clochepb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ClocheService_RunWorkflow_FullMethodName = "/cloche.v1.ClocheService/RunWorkflow"
	ClocheService_GetStatus_FullMethodName   = "/cloche.v1.ClocheService/GetStatus"
	ClocheService_StreamLogs_FullMethodName  = "/cloche.v1.ClocheService/StreamLogs"
	ClocheService_StopRun_FullMethodName     = "/cloche.v1.ClocheService/StopRun"
	ClocheService_ListRuns_FullMethodName    = "/cloche.v1.ClocheService/ListRuns"
)

// ClocheServiceClient is the client API for ClocheService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ClocheServiceClient interface {
	RunWorkflow(ctx context.Context, in *RunWorkflowRequest, opts ...grpc.CallOption) (*RunWorkflowResponse, error)
	GetStatus(ctx context.Context, in *GetStatusRequest, opts ...grpc.CallOption) (*GetStatusResponse, error)
	StreamLogs(ctx context.Context, in *StreamLogsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[LogEntry], error)
	StopRun(ctx context.Context, in *StopRunRequest, opts ...grpc.CallOption) (*StopRunResponse, error)
	ListRuns(ctx context.Context, in *ListRunsRequest, opts ...grpc.CallOption) (*ListRunsResponse, error)
}

type clocheServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewClocheServiceClient(cc grpc.ClientConnInterface) ClocheServiceClient {
	return &clocheServiceClient{cc}
}

func (c *clocheServiceClient) RunWorkflow(ctx context.Context, in *RunWorkflowRequest, opts ...grpc.CallOption) (*RunWorkflowResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RunWorkflowResponse)
	err := c.cc.Invoke(ctx, ClocheService_RunWorkflow_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clocheServiceClient) GetStatus(ctx context.Context, in *GetStatusRequest, opts ...grpc.CallOption) (*GetStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetStatusResponse)
	err := c.cc.Invoke(ctx, ClocheService_GetStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clocheServiceClient) StreamLogs(ctx context.Context, in *StreamLogsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[LogEntry], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ClocheService_ServiceDesc.Streams[0], ClocheService_StreamLogs_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamLogsRequest, LogEntry]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ClocheService_StreamLogsClient = grpc.ServerStreamingClient[LogEntry]

func (c *clocheServiceClient) StopRun(ctx context.Context, in *StopRunRequest, opts ...grpc.CallOption) (*StopRunResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StopRunResponse)
	err := c.cc.Invoke(ctx, ClocheService_StopRun_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clocheServiceClient) ListRuns(ctx context.Context, in *ListRunsRequest, opts ...grpc.CallOption) (*ListRunsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListRunsResponse)
	err := c.cc.Invoke(ctx, ClocheService_ListRuns_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ClocheServiceServer is the server API for ClocheService service.
// All implementations must embed UnimplementedClocheServiceServer
// for forward compatibility.
type ClocheServiceServer interface {
	RunWorkflow(context.Context, *RunWorkflowRequest) (*RunWorkflowResponse, error)
	GetStatus(context.Context, *GetStatusRequest) (*GetStatusResponse, error)
	StreamLogs(*StreamLogsRequest, grpc.ServerStreamingServer[LogEntry]) error
	StopRun(context.Context, *StopRunRequest) (*StopRunResponse, error)
	ListRuns(context.Context, *ListRunsRequest) (*ListRunsResponse, error)
	mustEmbedUnimplementedClocheServiceServer()
}

// UnimplementedClocheServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedClocheServiceServer struct{}

func (UnimplementedClocheServiceServer) RunWorkflow(context.Context, *RunWorkflowRequest) (*RunWorkflowResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RunWorkflow not implemented")
}
func (UnimplementedClocheServiceServer) GetStatus(context.Context, *GetStatusRequest) (*GetStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetStatus not implemented")
}
func (UnimplementedClocheServiceServer) StreamLogs(*StreamLogsRequest, grpc.ServerStreamingServer[LogEntry]) error {
	return status.Error(codes.Unimplemented, "method StreamLogs not implemented")
}
func (UnimplementedClocheServiceServer) StopRun(context.Context, *StopRunRequest) (*StopRunResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StopRun not implemented")
}
func (UnimplementedClocheServiceServer) ListRuns(context.Context, *ListRunsRequest) (*ListRunsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListRuns not implemented")
}
func (UnimplementedClocheServiceServer) mustEmbedUnimplementedClocheServiceServer() {}
func (UnimplementedClocheServiceServer) testEmbeddedByValue()                       {}

// UnsafeClocheServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ClocheServiceServer will
// result in compilation errors.
type UnsafeClocheServiceServer interface {
	mustEmbedUnimplementedClocheServiceServer()
}

func RegisterClocheServiceServer(s grpc.ServiceRegistrar, srv ClocheServiceServer) {
	// If the following call panics, it indicates UnimplementedClocheServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ClocheService_ServiceDesc, srv)
}

func _ClocheService_RunWorkflow_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RunWorkflowRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClocheServiceServer).RunWorkflow(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClocheService_RunWorkflow_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClocheServiceServer).RunWorkflow(ctx, req.(*RunWorkflowRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClocheService_GetStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClocheServiceServer).GetStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClocheService_GetStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClocheServiceServer).GetStatus(ctx, req.(*GetStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClocheService_StreamLogs_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamLogsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ClocheServiceServer).StreamLogs(m, &grpc.GenericServerStream[StreamLogsRequest, LogEntry]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ClocheService_StreamLogsServer = grpc.ServerStreamingServer[LogEntry]

func _ClocheService_StopRun_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StopRunRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClocheServiceServer).StopRun(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClocheService_StopRun_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClocheServiceServer).StopRun(ctx, req.(*StopRunRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClocheService_ListRuns_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRunsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClocheServiceServer).ListRuns(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClocheService_ListRuns_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClocheServiceServer).ListRuns(ctx, req.(*ListRunsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ClocheService_ServiceDesc is the grpc.ServiceDesc for ClocheService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ClocheService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "cloche.v1.ClocheService",
	HandlerType: (*ClocheServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RunWorkflow",
			Handler:    _ClocheService_RunWorkflow_Handler,
		},
		{
			MethodName: "GetStatus",
			Handler:    _ClocheService_GetStatus_Handler,
		},
		{
			MethodName: "StopRun",
			Handler:    _ClocheService_StopRun_Handler,
		},
		{
			MethodName: "ListRuns",
			Handler:    _ClocheService_ListRuns_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamLogs",
			Handler:       _ClocheService_StreamLogs_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "cloche.proto",
}
