package domain

import (
	"fmt"
	"strings"
)

// GenerateRunID produces a run ID using dashes as the delimiter so it is
// safe for use in filesystem paths. Format: <attempt>-<workflow> or
// <attempt>-<workflow>-<step>. The attempt segment is a 4-char random
// alphanumeric string generated by GenerateAttemptID.
//
// For display in CLI/API output, use FormatRunID to convert to the
// colon-delimited format (e.g. a12z:develop:implement).
func GenerateRunID(workflowName, stepName string) string {
	attempt := GenerateAttemptID()
	if stepName == "" {
		return fmt.Sprintf("%s-%s", attempt, workflowName)
	}
	return fmt.Sprintf("%s-%s-%s", attempt, workflowName, stepName)
}

// FormatRunID converts a dash-delimited internal run ID to the
// colon-delimited display format used in CLI output and API responses.
func FormatRunID(id string) string {
	return strings.Replace(id, "-", ":", 2)
}

// ParseRunID splits a run ID (either colon or dash delimited) into its
// attempt, workflow, and step components. The step component is empty if
// the ID has only two segments.
func ParseRunID(id string) (attemptID, workflowName, stepName string) {
	// Normalize: accept both colon and dash delimiters
	normalized := strings.Replace(id, ":", "-", 2)
	parts := strings.SplitN(normalized, "-", 3)
	if len(parts) >= 1 {
		attemptID = parts[0]
	}
	if len(parts) >= 2 {
		workflowName = parts[1]
	}
	if len(parts) >= 3 {
		stepName = parts[2]
	}
	return
}
