package domain

import (
	"fmt"
	"strings"
)

// GenerateRunID produces a run ID in the format <attempt>:<workflow>:<step>.
// The attempt segment is a 4-char random alphanumeric string generated by
// GenerateAttemptID. If stepName is empty, the step segment is omitted and
// the format is <attempt>:<workflow>.
func GenerateRunID(workflowName, stepName string) string {
	attempt := GenerateAttemptID()
	if stepName == "" {
		return fmt.Sprintf("%s:%s", attempt, workflowName)
	}
	return fmt.Sprintf("%s:%s:%s", attempt, workflowName, stepName)
}

// ParseRunID splits a colon-delimited run ID into its attempt, workflow, and
// step components. The step component is empty if the ID has only two parts.
func ParseRunID(id string) (attemptID, workflowName, stepName string) {
	parts := strings.SplitN(id, ":", 3)
	if len(parts) >= 1 {
		attemptID = parts[0]
	}
	if len(parts) >= 2 {
		workflowName = parts[1]
	}
	if len(parts) >= 3 {
		stepName = parts[2]
	}
	return
}
